### ISSUE TITLE
About page fix.

### ISSUE THREAD

**Issue by alaskalinuxuser** [renyuneyun/Easer#1]
Thanks for the app! 

I would like to help by filling in the about page.
The idea would be to add links to your github, website and the license as well as a brief app description. I plan to use strings so it is translatable. My hope is also to make it look aesthetically pleasing.

I will work on it and do a pull request.

**Comment by renyuneyun** [comment]
Glad you like this app and thanks a lot for your interest to help the development :)

**Comment by alaskalinuxuser** [comment]
I have submitted a pull request:

https://github.com/renyuneyun/Easer/pull/2

Also, I have no issue if you want to change anything. You are welcome to edit anything to suit your needs! :D
