### ISSUE TITLE
Unintuitive UI behaviour on configuration change

### ISSUE THREAD

**Issue by trikaphundo** [renyuneyun/Easer#10]
Hello, congratulation for your work.

The unintuitive behaviour can be reproduced as follows:
- open the drawer
- tap on either "Profile" or "Event"
- rotate the screen

After these steps, the "Outline" interface is shown but the user would expect the application to still show the previously chosen interface.
Keep in mind that screen rotation is just one of the several configuration changes that can produce this behaviour, such as a phone call

**Comment by renyuneyun** [comment]
Wow, seems I need to look into unpredictable human behaviors :P

Thanks for letting me know. It's due to the fact that I didn't explicitly save the state of every UI component, so when you rotate the screen they will be lost (because UI will be redrawn/reloaded).

I'll fix that in the near future, hopefully this week.

**Comment by trikaphundo** [comment]
Hahaha, rotating the screen is a good test to see whether an app is robust before configuration changes, a phone call while the activity is showing is pretty unlikely but possible, as other changes :)

Activities manage added fragments and their state, to a certain extent.
I have cloned your project, the problem is that EVERY TIME the main activity is created (onCreate(Bundle)), all fragments are removed and the "FRAGMENT_OUTLINE" is added to the activity. This can be solved by simply checking whether the app was abnormally terminated by the system: (if(savedInstanceState == null)...)

**Comment by renyuneyun** [comment]
Hmm, I didn't read those materials talking about how states are preserved / need to be preserved. That's another reason why I didn't add that part in the code in the first place.

Thanks for your pointing out.
Are there any general rules / behaviors about what states will be preserved by runtime / Android and what states need to be explicitly saved by developers? Then I can give a quick check over other components.

**Comment by trikaphundo** [comment]
I recommend reading the Android documentation; as a starting point [activity life-cycle](https://developer.android.com/guide/components/activities/activity-lifecycle.html#saras)
Essentially it says that the Android system will save and restore most of the state of the view hierarchy.

Fragments added to an activity are [stored as part of the activity state](https://developer.android.com/reference/android/app/FragmentManager.html#beginTransaction()) by the android system. Also, their [life-cycle](https://developer.android.com/guide/components/fragments.html#Lifecycle) is closely tied to the host activity's life-cycle and their handling is very similar to that of the activities

**Comment by renyuneyun** [comment]
Closed as of patch #11 (which is squashed to commit 9e9f0519a956c85eb8975a95c60cc42b0db79812).

Thanks for you work and recommendation :)
