### ISSUE TITLE
App crashes while clicking on added script with disabled plugin

### ISSUE THREAD

**Issue by pzdawood** [renyuneyun/Easer#101]
### Actual behaviour
When I open the easer app and open the options.i select settings option.then I open Enabled plugins and turn off time plug.then I go back to main menu.Again I click on options botton and select script option. Then I click on recent added script app crashes.
### How to reproduce
* Open the easer app.
* Click on options botton.
* Select settings option.
* Then click on enabled plugins option.
* Turn off time plug.
* Then back to main menu.
* Again click on options botton.
* Click select script option.
* Click on recent added script.
*After clicking on recent added script app crashes.
* Browser: Easer.
* Version:0.5.9.1
*Operating system: 7.1.2

### Recording of the bug
https://youtu.be/ObUrfdRQRx8

**Comment by renyuneyun** [comment]
One guess: is that script using an event which uses the *time* event?

If so, then you are reporting another corner case :P Yes they will be fixed.

**Comment by renyuneyun** [comment]
This should have been fixed in 0d1f1928447bae52213c7c62096f08e1a165310d which is a part of v0.6.1.
I'm closing this for now, but feel free to re-open if not fixed.

**Comment by renyuneyun** [comment]
(Since no new comments, I'll just leave my guess)

If my guess is correct, you are trying to use a script whose Scenario use TimeEventPlugin (which is disabled).

I'll prevent from disabling plugin in use.

**Comment by renyuneyun** [comment]
It's a long wait... But now (v0.7.6.2) this is finally fixed.
Feel free to reopen this if you can still disable a skill which is in-use.
