### ISSUE TITLE
Can not set the scenario time in landscape mode

### ISSUE THREAD

**Issue by neupanedipen** [renyuneyun/Easer#103]
#### Expected behavior<br>
I should be able to set the scenario time in every screen orientations.<br>
#### Actual behavior<br>
But the clock is hidden in landscape mode and doesn&apos;t appear in landscape mode which disallows me to set the scenario time in landscape mode. Even the full interface of calendar is not available in landscape mode.<br>
#### How to reproduce<br>
1. Install the app from Fdroid.<br>
2. Launch the app.<br>
3. Go to Scenario option from left sliding navigation bar.<br>
4. Click on + icon to create a new scenario.<br>
5. Now Change the orientation of the screen to landscape mode.<br>
6. Now slide to the left to Time bar to set the scenario time.<br>
The clock interface is blank in landscape mode.<br>
When you open the same option in potrait mode the clock appears and enables you to set the scenario time.<br>
* App Version: 0.6<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/kcgEdWoo-bM

**Comment by renyuneyun** [comment]
Thanks for reporting!
I'll look into that to see what I should adjust to fit landscape mode.

**Comment by renyuneyun** [comment]
Maybe 931cdf055ffea5c8ae14f771b4fd2f9a99f813c0 fixes this, together with #110 .
Please test after the relase is on repo...

**Comment by renyuneyun** [comment]
I'm closing this as it should have been fixed (?).

Feel free to reopen it :)
