### ISSUE TITLE
Half Clock and Calendar

### ISSUE THREAD

**Issue by organik1** [renyuneyun/Easer#110]
Hello dev.

My device carries a 5inches screen and is configured to about 240dpi.

This is an issue that exist in the portrait view of the app.

When I try to set the time  and date under `inline scenario` I notice that the clock and calender do not display in full. So it is practically impossible to pick values from this missing areas.

Here is a screenshot of the issue
https://ibb.co/cjXAGT

**Comment by renyuneyun** [comment]
Maybe related #103 
(Mainly as a not to myself)
