### ISSUE TITLE
Crash on script activation or daemon (re-) start

### ISSUE THREAD

**Issue by genodeftest** [renyuneyun/Easer#117]
Every time I try to start the daemon, the app crashes. This happened first when I had the daemon running and added a script. When disabling both of my scripts, the daemon runs fine. Once I activate any of them, the daemon crashes immediately.

Both scripts look like this:
* Title: some text
* Parent: None
* Profile: a WIFI profile (one of them is switching off mobile data)
* Radio buttons: Use scenario
* Reverse Scenario: no
* Scenario: Condition event
  * Condition: Cell Location
    * Cell ID: The cell I'm currently in
  * Type: Enter (the other script: Leave)

In other words: One script disables wifi when I leave my home mobile cell. The other script enables wifi when I enter my home mobile cell.

Backtrace:
```
05-30 21:07:11.996 11638 11638 D AndroidRuntime: Shutting down VM
05-30 21:07:11.997 11638 11638 E AndroidRuntime: FATAL EXCEPTION: main
05-30 21:07:11.997 11638 11638 E AndroidRuntime: Process: ryey.easer, PID: 11638
05-30 21:07:11.997 11638 11638 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=ryey.easer.service.action.REGISTER_CONDITION_EVENT flg=0x10 (has extras) } in ryey.easer.core.EHService$2@f71de57
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1323)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.$m$7(Unknown Source:4)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at android.app.-$Lambda$aS31cHIhRx41653CMnd4gZqshIQ.run(Unknown Source:39)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6501)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to android.app.PendingIntent[]
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at ryey.easer.core.EHService$2.onReceive(Unknown Source:96)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52497(LoadedApk.java:1313)
05-30 21:07:11.997 11638 11638 E AndroidRuntime: 	... 9 more
05-30 21:07:12.004  2390  3813 W ActivityManager:   Force finishing activity ryey.easer/.core.ui.MainActivity
05-30 21:07:12.008  2390  3813 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
05-30 21:07:12.016  2390  2504 I ActivityManager: Showing crash dialog for package ryey.easer u0
```

Installed version:
0.6.3 from f-droid

Android infos:
Version: 8.1.0, patchlevel 2018-05-01
Kernel: 3.18.71-perf

Device infos:
Nokia 5, model TA-1053

Is there any more info you need?

**Comment by renyuneyun** [comment]
Thanks for reporting! I think I know where this goes wrong from the log.

Just to confirm my guess, could you test:
1. When you use the "Condition Event" for a different type of Condition (e.g. battery status), will the crash happen?
2. When you use that Condition you defined directly (by selecting "Condition" in the radio buttons of Script), will the crash happen?

If I'm right, the first will crash for the same reason (the Exception will be the same); the second won't crash.

**Comment by genodeftest** [comment]
@renyuneyun : Neither of the two tests causes a crash.

**Comment by renyuneyun** [comment]
Hmm... That's strange. Anyway, I'll fix the problem I previously observe, and let's see what happens later.

**Comment by renyuneyun** [comment]
Does this still happen on v0.6.4?

**Comment by genodeftest** [comment]
The crash is fixed. Thank you very much!

I still don't get easer to work (i.e. the profile detection does not happen) but I'll need some time I don't have right now to track this down.
