### ISSUE TITLE
[FR] Check battery level

### ISSUE THREAD

**Issue by ChristianTacke** [renyuneyun/Easer#120]
Basicly, I would like to fire some actions, when the battery is getting below some value.

**Comment by renyuneyun** [comment]
Yes, that's one of the things I'd love to see too :)

**Comment by ChristianTacke** [comment]
After looking at https://developer.android.com/training/monitoring-device-state/battery-monitoring I think we should start by having a trigger on `BATTERY_LOW` and `BATTERY_OKAY`. These are really the most important events, especially the `BATTERY_LOW` one. People might want to disable stuff, if the battery is low.

There's even some commented out code in the current battery trigger: [BatteryTracker.java line 55](https://github.com/renyuneyun/Easer/blob/master/app/src/main/java/ryey/easer/skills/usource/battery/BatteryTracker.java#L55)

The UI could be extended to not only have "charging" and "discharging", but also "low" and "okay". This is hopefully straightforward.

What do you think?

**Comment by renyuneyun** [comment]
Forgot to update: this has been implemented (I didn't remember the version, please check the changelog).

I'm assuming this is fixed, and will close it if no complaint happens.

**Comment by ChristianTacke** [comment]
I have seen it in the current version. Did not yet get to testing it.
Closing it as "implemented".
If I notice, that it's not working, I'm going to file a bug report.
