### ISSUE TITLE
Time condition

### ISSUE THREAD

**Issue by qoheniac** [renyuneyun/Easer#123]
A condition for time intervals would be nice so you can do things like activating “Do not disturb” when connecting to WiFi at home but only if its not between 6 am and 10 pm.

**Comment by renyuneyun** [comment]
v0.6.5 should make this done. Please have a try after it shows up on F-Droid.

**Comment by qoheniac** [comment]
Nice this feature was added that fast. Up till now it seems to work, but there were two things I observed:

1. I changed an existing script from using a time scenario to using a time condition and Easer crashed. This did not happen when I created a new script, but it seems to work in both cases anyway. I will try to provide a minimal step by step example to reproduce this later.

2. Why is there this single “After” radio item? It is not activated when creating a new time conditionen and once activated it cannot be undone. This seems very odd and it is unclear what it means to leave it deactivated.

**Comment by qoheniac** [comment]
Ok the crash only happens if you tell an already existing script to use a condition never used before by any script. So you can reproduce the crash with the following steps:

1. Create a script foo
2. Create any condition bar (tested it with time and date)
3. Make foo use bar
4. Crash

A few notes:

1. After restarting the app everything works just fine.
2. If the condition was used before in any script the crash won't happen.
3. If you use the newly created condition in a newly created script the crash also won't happen.

I am using Android 6.0.1.

**Comment by qoheniac** [comment]
Another thing: As there is no “Before” option I thought this is implemented through the “Reverse Scenario” feature but I just realised this does not work.

**Comment by qoheniac** [comment]
While not 100% sure, the reverse scenario toggle seems to work since the last update. The crash on the other hand still happens, but isn't a big problem. Still it's probably confusing to new users.

**Comment by renyuneyun** [comment]
I'm closing this as it should have been fixed (?).

Feel free to reopen it :)
