### ISSUE TITLE
[FR] record cell location for given timespan

### ISSUE THREAD

**Issue by wangongtsen** [renyuneyun/Easer#125]
I want to use easer to control things like Wi-Fi on/off and ringer mode based on my location using cell towers. To set this up, I need to know all the cell IDs my phone is able to connect to from a certain location. Monitoring and adding these by hand is almost impossible.
So a feature to record all cell IDs my phone will connect to within the next x hours/minutes and add them to a scenario would be great. Another useful addition would be a log of cell IDs from which one can add a selection of or single IDs to a scenario.

**Comment by renyuneyun** [comment]
Actually I'm thinking about that too!

**Comment by renyuneyun** [comment]
Done in 33492e6e (v0.7.2.3) :)
