### ISSUE TITLE
Condition: WiFi Connection

### ISSUE THREAD

**Issue by sphh** [renyuneyun/Easer#128]
Before the last update, I had the following settings:

`Profile` "Turn WiFi off":
- `WiFi off`

`Scenario` "Home WiFi":
- `WiFi Connection – Match SSID (ESSID)` with my home WiFi SSID

`Script` "When loosing home WiFi":
- `Parent`: None
- `Profile` "Turn WiFi off"
- `Use Scenario`
- `Reverse Scenario` active
- `Scenario` "Home WiFi"
- `Repeatable when satisfied` off
- `Volatile`

With this setting, my phone switches off the wireless connection whenever it looses connection to the home WiFi to save power.

After the update to v0.6.5 I transferred my **Scenario** "WiFi Connection – Match SSID (ESSID)" to a **Condition** "WiFi Connection – Match SSID (ESSID)" with exact the same settings. I also changed the `Script` to use the condition instead of the scenario.

When I start Easer whenever I have the WiFi connection up and running, everything works as expected and the wireless gets powered off as soon as the phone cannot see the home WiFi.

The problem starts when my phone tries to connect to my home WiFi with Easer running: Everything works fine until somewhere during the connection process the wireless adapter is switched off by my script "When loosing home WiFi". It looks to me that the condition is somewhere fired during the connection process.

Is this behaviour intended?

**Comment by renyuneyun** [comment]
I think this indicates a bug.

Is the last situation like the following?:
1. WiFi adapter is off
2. Start Easer
3. Turn the WiFi adapter on
4. Problem happen

If so, then I think maybe I can pin point it.

**Comment by sphh** [comment]
Yes, you are right with your description of the situation.
