### ISSUE TITLE
Profile with action "Send Broadcast" makes Easer crash

### ISSUE THREAD

**Issue by kaefert** [renyuneyun/Easer#129]
It would be very nice if we could make the device ring right in the second when a profile matches.
Preferable with an option to choose which ringtone (sound-file?) should be played.

The closest I could find at the moment is to set a relative alarm with time = "00:01" which makes the phone ring 1 minute afterwards. Setting a relative alarm with "00:00" makes it ring 24 hours later.

**Comment by kaefert** [comment]
Okey so I found I can play a ringtone using this on the command line:
`am start -a android.intent.action.VIEW -d file:///system/media/audio/ringtones/New_Beginning.ogg -t audio/wav`
Let's see if I can adept this as a step in an Easer Profile...

**Comment by kaefert** [comment]
Creating a Profile with the Action "Send Broadcast" with
Action = "android.intent.action.VIEW"
Category left empty
Data = "file:///system/media/audio/ringtones/New_Beginning.ogg"
Type = "audio/wav"

Will make Easer crash every time one opens that profile after it's saved. Also it doesn't work when used by a Script.

**Comment by kaefert** [comment]
I also tried making a Profile with the Action "Run commands" with the textfield set to `am start -a android.intent.action.VIEW -d file:///system/media/audio/ringtones/New_Beginning.ogg -t audio/wav`
That can be saved and opened without a problem, but it also doesn't seem to do the trick although that command works fine for me over an adb shell.

**Comment by kaefert** [comment]
Perfect! I can now create and edit and view profles with the send broadcast option.

Sadly I could not test if it also does what it should yet, because of this issue:
https://github.com/renyuneyun/Easer/issues/134

**Comment by ildar** [comment]
Getting back to the original feature request, I expected that "Send
notification" profile would play sound but it didn't. I guess that it needs
improving: besides custom notification sound I'd suggest (1) having actions
on notification tap and dismissal, (2) showing toast
-- 
Ildar Mulyukov,
(ΙΧΘΥΣ) child of God

email: ildar.mulyukov@gmail.com
matrix: @ildar:matrix.org
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by kaefert** [comment]
Hey ildar, I'm sorry that we changed this ticket from the Feature Request it originally was to a bug issue that got fixed and therefore closed this issue.

I've opened a new issue for the original Feature Request explaining what happened until now here:
https://github.com/renyuneyun/Easer/issues/137
