### ISSUE TITLE
Crash on adding cell in airplane mode

### ISSUE THREAD

**Issue by wangongtsen** [renyuneyun/Easer#131]
Steps to reproduce:
activate airplane mode on phone, open any event in easer and press the button to add a cell in "Cell Location"-tap

Expected Results:
don't do anything or point to activated airplane mode

Actual Results:
app crashes and restarts normally, no cell added

easer v0.6.6
LineageOS v14.1

**Comment by renyuneyun** [comment]
Wow, I'm so careless to bury this in the list :o/

Thanks for reporting! This indeed needs to be fixed.
