### ISSUE TITLE
Log the activity of Scripts (start to listen, etc)

### ISSUE THREAD

**Issue by ildar** [renyuneyun/Easer#132]
I mean that timer start should at least be in activity log. Better with ETA.

**Comment by ildar** [comment]
+ to run (again) a script with timer I need what? rerun the whole Easer?

**Comment by renyuneyun** [comment]
So you are thinking of a full-function log. Seems to be a good idea.


What kind of run-again do you mean? Allow it to run again after timer is met (e.g. run it every 5 minutes)?
If so, make it "repeatable" should do.

**Comment by ildar** [comment]
The initial issue was: I set up a timer event (or script) but don't have
any info about when it started and going to end. So I suggest to show the
timer info somewhere in some way.

**Comment by ildar** [comment]
On re-running: that was more of a question whether I can control the timer
start. The answer I got to: no, it starts on service start but
alternatively can be started by an external event, e.g. broadcast receive

**Comment by renyuneyun** [comment]
Hmm, this seems to be more than I thought.
What I thought is:

> Script ABC starts to listen at 1:2:33
> Script ABC is satisfied at 1:3:44
> Profile MN is loaded by Script ABC at 1:3:45
> Script XYZ stops to listen at 1:4:11

**Comment by ildar** [comment]
when this'll be implemented, I hope to see why (and when) my timer script
triggered multi-times while it is set "Inexact, One time"

**Comment by ildar** [comment]
+ please add service start and stop entries

**Comment by renyuneyun** [comment]
I think this is already implemented (for a while),,, forgot to mention.

Shall this issue be closed？
