### ISSUE TITLE
Condition: WiFi Connection [reopen]

### ISSUE THREAD

**Issue by sphh** [renyuneyun/Easer#133]
Reference: #128 

@renyuneyun, thanks for working on this bug. I upgraded Easer from F-Droid to version 0.6.6.1. Unfortunately it still does not work as I would expect. This is what happens with the settings as in #128 :

1. WiFi is switched off.
2. I start Easer.
3. I manually switch WiFi on.
4. WiFi tries to connect, but then Easer switches off WiFi (Easer shows the corresponding profile and From in the main screen).

Easer works fine and switches off WiFi, if my phone looses the contact with the wireless network. The problem seems to be in the phase when WiFi negotiates with the the server. It looks like Easer gets a notification, that the WiFi connection closed during this time.

Would a logfile help? (Then I have to find a SD card ...)

**Comment by renyuneyun** [comment]
Thanks for reporting. It seems I still didn't handle the wifi broadcasts correctly... (Though I thought I have tested all the cases...)

I'll try to figure it out. Logfile is not needed, as it won't help (because nothing related to this is logged).

**Comment by sphh** [comment]
Thank you for looking into this. I don't know if this is still important, but in my `Script` I have ticked `Use Condition` (and not `Inline Event` or `Predefined Event`) and this uses a Condition and not Event/Scenario.
