### ISSUE TITLE
[FR] Make device ring (play sound) now

### ISSUE THREAD

**Issue by kaefert** [renyuneyun/Easer#137]
I would like to make my device ring (play a sound) right in the instance when some profile matches.

Using an ADB shell, I found I can play an arbritrary sound file using this command:
`am start -a android.intent.action.VIEW -d file:///system/media/audio/ringtones/New_Beginning.ogg -t audio/wav`

For some reason though, pasting that same command into an easer "Run commands" profile doesn't do anything (no error, no sound).

Also a profile with a "Send Broadcast" item with Action = "android.intent.action.VIEW", Type = "audio/wav", Data = "file:///system/media/audio/ringtones/New_Beginning.ogg" doesn't do anything (no error, no sound).

Does anybody have an idea how to debug this, or an idea how else to get that feature?

An alternative Feature Request from user Ildar in the previous issue https://github.com/renyuneyun/Easer/issues/129 was to extend the Notification functionality so that it does not only show a configured text but also plays a sound.

**Comment by renyuneyun** [comment]
Thanks for (re)opening this!

I nearly forgot this ;-0

**Comment by kaefert** [comment]
Is this maybe the reason the send broadcast doesnt work?

```
07-14 11:38:14.011 10249 10252 E PRETTY_LOGGER: │ error while loading operation <b> for profile <ringNow> : java.lang.NullPointerException: Attempt to read from field 'java.lang.Integer ryey.easer.plugins.operation.p.b.a' on a null object reference
07-14 11:38:14.011 10249 10252 E PRETTY_LOGGER: │ 	at ryey.easer.plugins.operation.p.a.a(Unknown Source)
07-14 11:38:14.011 10249 10252 E PRETTY_LOGGER: │ 	at ryey.easer.plugins.operation.p.a.a(Unknown Source)
07-14 11:38:14.011 10249 10252 E PRETTY_LOGGER: │ 	at ryey.easer.core.ProfileLoaderIntentService.a(Unknown Source)
07-14 11:38:14.011 10249 10252 E PRETTY_LOGGER: │ 	at ryey.easer.core.ProfileLoaderIntentService.onHandleIntent(Unknown Source)
07-14 11:38:14.011 10249 10252 E PRETTY_LOGGER: │ 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
07-14 11:38:14.011 10249 10252 E PRETTY_LOGGER: │ 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-14 11:38:14.011 10249 10252 E PRETTY_LOGGER: │ 	at android.os.Looper.loop(Looper.java:154)
07-14 11:38:14.011 10249 10252 E PRETTY_LOGGER: │ 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by renyuneyun** [comment]
So a dedicated Operation is added in v0.7.3.

The bug above should be related to broadcast operation. There were a few issues about that, and should have been fixed already.
