### ISSUE TITLE
[CRASH] Dynamics Link button in a script

### ISSUE THREAD

**Issue by ildar** [renyuneyun/Easer#142]
if script is "old", i.e. from the previous version of Easer.
Data conversion processed but may be incomplete.
[adb.logcat.log](https://github.com/renyuneyun/Easer/files/2187380/adb.logcat.log)

**Comment by ildar** [comment]
+logger
[logs_0.csv.log](https://github.com/renyuneyun/Easer/files/2187430/logs_0.csv.log)

**Comment by renyuneyun** [comment]
So this should have been fixed in v0.6.7.2 .
Please have a test and report back (after it appears on f-droid).
(Or try [this one](https://bintray.com/renyuneyun/Android/download_file?file_path=Easer-v0.6.7.2.apk) signed by me.)
