### ISSUE TITLE
Use root features

### ISSUE THREAD

**Issue by twikedk** [renyuneyun/Easer#145]
If I enable 'Use root features' then leave settings page and return to settings page again, it doesn't show enable anymore.

Running v0.6.7.2
Android 5.1

**Comment by renyuneyun** [comment]
First of all: is you device rooted?

If yes, have you ever rejected to grant Easer root permission in the root manager (e.g. SuperSU)?

(The root feature shouldn't have any problem as it wasn't touched after implemented.)

**Comment by twikedk** [comment]
Oh my, I always thought 'Use root features' as a not needing a rooted phone but kind of root on user level to help in special occasions :-)

**Comment by renyuneyun** [comment]
LOL

I would call that "advanced features" :P  

After all, "root" is a special (and defined) thing in unix.
