### ISSUE TITLE
Condition/Event: WiFi Connection

### ISSUE THREAD

**Issue by sphh** [renyuneyun/Easer#149]
Unfortunately I still have the same issues in version 0.6.7.2 as described in #128 and #133.

I tried to solve it by using an `Event` or a `Condition`, but in both cases the WiFi shutdown script get triggered during negotiation of the WiFi connection.

I am more than happy to provide you with any further information; please tell me how to provide it.

**Comment by ildar** [comment]
Then why are you cloning duplicates? Just reopen the old bug or ask to do
that

**Comment by sphh** [comment]
@ildar, that's easy: I am not allowed to reopen the old bug. Since my request to reopen it remained unanswered, so I thought it's best to open a new one so that it does not get forgotten. If you have the power to reopen the old bug(s), please feel free to do so and close this one. Thanks.

**Comment by renyuneyun** [comment]
For github: That's strange, you should be able to reopen your issues.
(I don't see anything called "request for reopen", unless manually write that...)

The bug is still strange, since I couldn't reproduce it...

Are you familiar with android programming? I guess it's best to debug on your side where the bug can happen... I can give you instructions on where debug sentences should be added.

**Comment by ildar** [comment]
Logcat should be helpful

**Comment by sphh** [comment]
I finally managed to get a logcat with the following steps on my Android phone:

1. I enabled Easer by tapping the big red cross.
2. The wireless was switched off. I started it by pulling down from the top and tapping the WiFi icon.
3. Here it should connect automatically to my wireless network. I could see the `?` for some seconds, then the WiFi switched off.
4. The Easer Outline screen tells me that the profile "Switch WiFi off" was loaded at 10:12:25.

@renyuneyun: I have never programmed for the android, but I am fairly fluent on Linux system. If you tell me what to do, I could give it a try.

**Comment by renyuneyun** [comment]
I created a test version, which may improve the situation. Would you like to give it a try? (Note this .apk is signed by me, not f-droid.)

[Easer-v0.6.9.1-alpha.zip](https://github.com/renyuneyun/Easer/files/2321006/Easer-v0.6.9.1-alpha.zip)

**Comment by sphh** [comment]
Thanks. I downloaded the .zip file, unpacked it and tried to install the .apk, but I get the following error message:

```
Package Installer

This is a package installer. What action would you want to perform?

INSTALL  VIEW  CANCEL
```
I pressed `INSTALL`.

```
Easer

Do you want to install an update to this existing application? Your existing data will not be lost. It does not require any special access.

CANCEL INSTALL
```
I pressed `INSTALL`.

```
Easer

App not installed.

DONE
```

Do I have to de-install `Easer` which was installed with F-Droid? (In this case I will loose all scripts/conditions/settings/... won't I?)

**Comment by renyuneyun** [comment]
Yes, you have to uninstall and install again, which is what "signed by me, not f-droid" suggests (two different signatures).
You can always export all your data of Easer (and then import), at the bottom of the Settings page. This includes everything except for your settings (which isn't a lot, and some require additional setting outside of Easer).

**Comment by sphh** [comment]
Thanks. I missed that option in the Settings page ...

I re-installed you alpha version. I tested it a couple of times and it seems to work now as expected:

- I can switch on WiFi on my Android phone and it connects to the already up and running WLAN.
- I can switch on the WLAN router and the already running WiFi on my Android phone connects.

Thank you so much!

**Comment by sphh** [comment]
This runs stable since the alpha version (I am now on v0.7.0.2), so I close this issue.

Thanks!!
