### ISSUE TITLE
[FR] Add Condition "Wifi enabled" and "Bluetooth enabled"

### ISSUE THREAD

**Issue by ghrandt** [renyuneyun/Easer#152]
Hi. I want to achieve the following: 
1) Whenever WiFi gets enabled: 
[Event] Enter condition "Wifi enabled" -> Wait 1 minute -> Check whether WiFi is connected (via Connectivity Type). If no, disable WiFi.
2) Whenever WiFi connection is lost for a minute -> Disable WiFi.
(+ The same for Bluetooth.)

The idea behind this is to disable WiFi/Bluetooth automatically whenever it is not needed (without specifying cell tower IDs for various locations), even if WiFi/Bluetooth are enabled by mistake. 

I have two problems implementing the above. 
-  It seems that 2) can be implemented using the current features but I did not find a way that works. Since a script only allows 1 event or 1 condition, my idea was to create "Script 1" with no parent and no profile. Script 1 goes off whenever the event "Leave conditon 'Connectivity Type: Wifi'" occurs. As I would like to have the time delay, I probably need "Script 2" with "Script 1" as its parent that just waits for 1 minute (Event -> Timer -> 1 Minute) and a "Script 3" with "Script 2" as its parent that checks WiFi connectivity again and finally disables WiFi. However, Script 2 never activates. The log says that Script 1 gets triggered if WiFi connection is lost. However, it immediately changes its status to "unsatisfied" because the connection is already lost, probably preventing Script 2 from firing. Any help with this would be much appreciated.
- As "Connectivity Type: Wifi" only trips if a WiFi connection is established (or lost), I did not find a way to implement 1). 

Would it be possible to add a new condition that checks whether WiFi (or Bluetooth, for that matter) is enabled?

**Comment by renyuneyun** [comment]
Hi there,

Glad you have investigated so much. You are actually one step near success if I understand correctly.
You'll need to use *Condition* for you "Script 1", instead of *Event*. (Or you can also use Event with "persistent" set to true, though this is strongly encouraged to be replaced by using Condition instead.)

For "Wifi enabled" and "Bluetooth enabled": yes I think they shall be added as new Conditions. (I'm planning to use Condition as much as possible where appropriate, instead of Event.)

**Comment by ghrandt** [comment]
Hi, thank you very much for your response. Indeed I was playing around some more and it seems I got 2) to work (using the delay makes it a workaround for people having problems with "turn Wifi off" scripts going off while connecting to a Wifi AP). 

I used the following method:

1) Create **Condition** "C:Wifi connected" with only `Connectivity Type: WiFi` selected.
2) Create **Event** "E:Lose Wifi" with `Condition Event: C:Wifi connected` and `Leave` selected.
3) Create **Script** "S1:Lose Wifi" with `Parent: None`, `Profile: None` and `Predefined Event:E:Lose Wifi` with `Reverse Scenario: ON`.
4) Create **Script** "S2:Lose Wifi for 1 minute" with `Parent: S1:Lose Wifi`, `Profile: None` and `Inline Event: Timer` with `Repetive timer? = One time` (possible typo, should be "repetitive") and `1 Minute`.
5) Create **Script** "S3:Check Wifi again" with `Parent: S2:Lose Wifi for 1 minute`, `Profile: Turn off Wifi` (which does exactly that) and `Use condition: C:Wifi connected` with `Reverse Scenario: ON`.

So I did use a condition in Script 3 and I kind of used a condition in Script 1 (well, an event that triggers when leaving the condition). However, if I use the same condition in Script 1 as I did in Script 3, the logs fill up saying `Script S:Lose Wifi, Status: Unsatisfied` twice a second. This made me think that it would also use up a lot of battery. To me, using the event that checks for leaving a condition seems a more intuitive approach, but maybe I am wrong. In this case please correct me. 

What I was wondering is that I needed to turn on `Reverse Scenario: ON` in Script 1, which makes no sense to me (since I want it to activate whenever I leave the condition). If i deactivate it, the log shows `Script S:Lose Wifi, Status: Unsatisfied` whenever a disconnect happens, and Script 2 never fires. If I activate it, the log shows the above message on connecting to a Wifi network and Script 2 fires after a disconnect, as desired. 

Thanks again for your help.

**Comment by sphh** [comment]
Nice thinking, @ghrandt ! thank you for giving this example. I now use the same approach for switching WiFi off and it works since #149 was resolved, so IMHO this issue can be closed.

@renyuneyun , maybe you want to include this in your wiki, since it looks to be quite a common request ...

**Comment by renyuneyun** [comment]
Hiya,
WifiEnabledCondition and BluetooehEnabledCondition has been added in v0.7.1 ;)

I think this issue can be closed?

**Comment by ghrandt** [comment]
Hi, after I saw the new features added (thank you so much for implementing them!), I immediately started testing. In this post, I will describe the problems (and solutions) I encountered and found. 

TL/DR:

- The WifiEnabledCondition works as expected.
- The combination of two tasks (Disable Wifi on Losing connection for a while, see https://github.com/renyuneyun/Easer/issues/152#issuecomment-413325302) + Disable Wifi if, after enabling, no connection is established after a short time) was a bit tricky, but I got it to work.
- (probably unrelated **bug**): App crashes whenever a **Profile** wants to set the status of any **Script** to "Unsatisfied" (Control Script Node Status Feature).

In more detail:
With regards to Wifi, I wanted to accomplish two goals (see https://github.com/renyuneyun/Easer/issues/152#issue-349664856):

1. Disable Wifi if, after enabling Wifi, no connection is established within 1 minute. (Useful if Wifi is turned on by accident)
2. Disable Wifi after connection is lost for a while (e.g., 1 minute)

I think I have found a way to do that, but it was a bit tricky. For the second goal, I use the procedure described in https://github.com/renyuneyun/Easer/issues/152#issuecomment-413325302. With the new feature _WifiEnabledCondition_ I thought the following would take care of the first goal:

1. Create **Condition** "C:Wifi enabled" with `WiFi Enabled: Yes`.
2. Create **Event** "E:Enable Wifi" with `Condition Event: C:Wifi enabled` and `Enter` selected.
3. Create **Script** "S:Wifi gets enabled" with `Parent: None`, `Profile: None`,`Predefined Event: E:Enable Wifi` and `Repeatable: OFF.`
4. Create **Script** "S:Wifi enabled for 1 minute" with `Parent: S:Wifi gets enabled`, `Profile: None` and `Inline Event: Timer` with `Repetitivetimer? = One time` and `1 Minute`.
5. Create **Script** "S:Check Wifi again after enabling" with `Parent: S:Wifi enabled for 1 minute`, `Profile: Turn off Wifi` (which does exactly that) and `Use condition: C:Wifi connected` with `Reverse Scenario: ON`. (from https://github.com/renyuneyun/Easer/issues/152#issuecomment-413325302)

The procedure above works for accomplishing the first goal. Accidental activations of Wifi are a thing of the past now. However, I have encountered the following problem with regards to the interaction with my set of scripts for goal no. 2: Whenever I lose a connection, the Script "S:Check Wifi again after enabling" would kick in **without the 1 minute delay** and turn off Wifi immediately. This is a problem since I sometimes lose the connection due to low signal for a few seconds. What I think happens is the following:
The **Script** "S:Wifi gets enabled" is satisfied. After 1 minute, the **Script** "S:Wifi enabled for 1 minute" is satisfied as well. From now on, whenever a connection is lost, **Script** "S:Check Wifi again after enabling" triggers. If I'm right, **this is not a bug**. 

Yet, it would be nice to have the option to check for a condition only at a certain time and if this condition is not met at that time, not check it again until the parent script triggers again. I have tried to accomplish that using the following workaround: 

1. Create **Profile** "Manipulate Wifi" with `Control Script Node Status` and choosing `Unsatisfied` for `S:Wifi gets enabled`.
2. Create **Script** "S:Wifi gets connected" with `Parent: S:Wifi gets enabled`, `Profile: Manipulate Wifi` and `Inline Event: C:Wifi connected: ENTER`

The idea was to "deactivate" the parent script such that **Script** "S:Check Wifi again after enabling" does not trigger immediately anymore whenever a connection is lost. I don't need it anymore since the other set of scripts take care of that and whenever I reactivate Wifi, everything is in place again. **However, the app crashes whenever the **Profile** "Manipulate Wifi" is triggered.** I have tried to set other scripts to the "Unsatisfied" state - the app always crashed. This is probably unrelated but I still wanted to share the bugreport in this issue. 

Finally, the "solution" that works for me: 
In the **Script** "S:Wifi gets enabled", set `Parent: S3:Check Wifi again` (from https://github.com/renyuneyun/Easer/issues/152#issuecomment-413325302)
The (tiny) downside is that after every restart of Easer, a Wifi connection has to be established before the the set of scripts protecting from accidental activation of Wifi can kick in. Since I rarely restart Easer and often connect to a Wifi, this is not an issue and still a big improvement compared to how it was before. 

If anyone has a better implementation idea, please share it - I'm sure I'm not the only one interested in this. Otherwise, I think this issue can be closed.

**Comment by renyuneyun** [comment]
Hi @ghrandt , I didn't notice your comment previously, apologise. I believe you mean "freeze" and then ANR, rather than crash immediately? If so, this is fixed in 1695b957 which is going to be shipped with v0.7.2.4 .
I'm closing this issue, but feel free to reopen it if the issue described in the title is still there. Or, please open another issue.
