### ISSUE TITLE
Incorrect check of ringer mode toggle permission

### ISSUE THREAD

**Issue by bughunter2** [renyuneyun/Easer#154]
Hi,

It appears I can only **enable** the Do Not Disturb (DnD) mode with the Ringer Mode operation.
I can't **disable** DnD mode.

Is that correct? If so, I'd like to request this as a feature, to be able to disable DnD mode.

(I was using Android 6.0.1)

**Comment by renyuneyun** [comment]
Hi there,
I don't quite get the point...
Isn't "setting phone to 'normal' mode" (or vibrate) the reverse to "enable DnD"? Or, doesn't that work on you device?

**Comment by bughunter2** [comment]
Hi @renyuneyun 

I understand what you're saying. And at first, I thought the same thing. So I tested setting it to Normal (or Vibrate) mode via the Ringer Mode operation, but even then the DnD stayed active (it already was active and it stayed active).

Next thing I tried was to disable the DnD "planning/schedule" checkbox, so that my phone wouldn't automatically enable or disable DnD mode. Because who knows, maybe it interfered. But it didn't interfere. Even with the DnD "planning/schedule" checkbox cleared (or disabled), the DnD mode stayed active when Easer's Ringer Mode operation got activated (even though I set the Ringer Mode to Normal).

I'm hoping someone can reproduce this behavior, either via an emulator or a real device. Again, my Android version is 6.0.1.

**Comment by renyuneyun** [comment]
That seems weird.
I'm using Android 6.0.1 too (Oxygen OS). This works as expected on my phone.

However, have you tried to select "all" for "DnD"? IIRC, this represents disabling DnD mode.

Just to check: Which type of DnD are you using for the test?
(Actually on my device, there are only "prioritized" and "alarm" DnD modes.)

**Comment by bughunter2** [comment]
I've made a Profile with the following settings but it did not help:

Title: test-dnd
Ringer Mode: Do not disturb
Ringing items in Do not Disturb mode: All

To test it, I've triggered the operation manually by long-tapping it and choosing Trigger this Profile.

This seems to do nothing at all on my device. DnD mode stays active if it already was.

I've also tried to do the reverse: To let Easer activate DnD mode rather than disable it. However, Easer won't enable (or disable) DnD mode on my device at all.

I've tried all of the Ringer Mode settings (DnD All, DnD Priority, DnD None, DnD Alarms).
I'm sorry to say that none of them do anything on my device.

**Comment by renyuneyun** [comment]
Sorry for the long delay.

I just realized that I forgot to ask: have you grant Easer the pemission to toggle DnD mode?

**Comment by bughunter2** [comment]
Yes. The ability to control the DnD mode is listed as a capability in the app's permissions, under the heading "Other app capabilities".

**Comment by bughunter2** [comment]
This is solved.
In Android's "Notification access" settings, enabling Easer's "Silent Mode Switcher" permission solved the problem. That was all that was needed.
I didn't enable this setting the moment it was shown to me when launching Easer for the first time, and never looked at it again until now.
(To emphasize, enabling this setting was needed even if the ability to control DnD mode was already listed as a permission under "Other app capabilities" in the app's permissions.)

**Comment by renyuneyun** [comment]
Yes, permission control was officially added in Android 5.0 (though it was already partially hidden available in 4.4) Every sensitive permission needs to be granted by the user **manually**. The app's permission list is only a declaration of the maximum capability / requirement.

But it is indeed a problem that the check of permission (of ringer mode) is incomplete in Easer. I'll figure it out.

**Comment by renyuneyun** [comment]
The real bug may be fixed in v0.7.1.1. Feel free to reopen this issue if otherwise.
