### ISSUE TITLE
can't add multiple Ringer Mode operations to a Profile

### ISSUE THREAD

**Issue by bughunter2** [renyuneyun/Easer#155]
The idea is to be able to add two or more "Ringer Mode" operations to a single Profile.

The reasoning behind this is that you may want to create a Profile that puts your phone both on Vibrate AND disables the Do Not Disturb mode as well, in one Profile.

To accomplish this, you have to be able to add multiple "Ringer Mode" operations.

At the moment however, when you add a single "Ringer Mode" operation, you can't add it once more.

However, other operations can be added multiple times without a problem. For example, the "Adjust Volume" and "Car Mode" operations can be added multiple times.

I'd like this to be possible with the "Ringer Mode" operation as well, so I can add it multiple times to a single Profile.

**Comment by renyuneyun** [comment]
Hmm, doesn't setting ringer mode to "vibrate" disable DnD mode automatically?

**Comment by bughunter2** [comment]
For me, it doesn't. (Even though the permissions are granted.)

**Comment by renyuneyun** [comment]
Then this seems to be a bug. I think there is a general fix. I'll include it in the next fix release.
If still doesn't fix, I'll allow Ringer Mode to be added multiple times.

**Comment by bughunter2** [comment]
Hmm, I'm not sure.

Perhaps it is a good idea to allow Ringer Mode to be added multiple times, and not fix this.

The reasoning behind this is:
If you fix this issue, people can't set the phone to vibrate using Ringer Mode without causing side effects. The side effect of course is that the Do Not Disturb mode will be disabled.
This limits the number of possible configurations people can make with Easer.

Fixing this issue in the said way could cause problems.

Imagine the following scenario:
One has set up a Script to set the phone to vibrate every night at 01:00.
They have this Script because they want to be sure the phone is set to vibrate when they wake up in the morning (for instance because they turned off sound/vibrations during the day).
During the night, their phone has the Do Not Disturb mode enabled (via the Android schedule).
Then, in that scenario it may become impossible for them to use Easer to set the phone to vibrate, because Easer would also disable the Do Not Disturb mode. But they don't want to be woken up during the night, so that's a problem.

If the above is true, then maybe it's better to just leave this issue as-is, and allow Ringer Mode to be added multiple times.

Or, maybe there's another way to fix the issue. For example, you could add a checkbox to the Ringer Mode UI, which allows you to BOTH set the phone to vibrate AND disable DnD in a single Ringer Mode operation. (The checkbox could have the text "Also set Do Not Disturb mode" or something similar.)

**Comment by renyuneyun** [comment]
I'm closing this issue because it's solved (IIRC).

Feel free to re-open it :)
