### ISSUE TITLE
[feature request] sms forward

### ISSUE THREAD

**Issue by kaefert** [renyuneyun/Easer#164]
I can create events for receiving sms and profiles for sending them, but I can't find a way to access the text of the received sms for reusing it in the sent sms (=forward content)

Would it be possible to have a variable to use the content of the received sms from the event in the send sms in the profile?

**Comment by renyuneyun** [comment]
Both yes and no.

yes: the *mechanism* to do this is implemented. see Dynamics on [this page](https://renyuneyun.github.io/Easer/en/FEATURES.html) for a little more details.
no: SMS Event does not yet support Dynamics. This will be added recently. (Actually this is trivial, but I'm working on something else at the moment.)

**Comment by renyuneyun** [comment]
Maybe one more thing worth mentioning: currently the Profile can only utilize Dynamics of the Event/Condition in the *same* Script (and core Dynamics). This is expected to be improved in the future.

**Comment by renyuneyun** [comment]
This is added in v0.7 :P

It will take a few days to appear on f-droid.

**Comment by kaefert** [comment]
Wow! you're amazing! Will try it as soon as I get it through f-droid!
