### ISSUE TITLE
 events should have an active/inactive setting

### ISSUE THREAD

**Issue by p2635** [renyuneyun/Easer#18]
Otherwise i have to delete the event and remake it if i want it

**Comment by renyuneyun** [comment]
Yup, that's not difficult and I'll try to create the next release (and include this in) in the following days.

The only problem is still the semantics (which is the reason why I removed enabled/disabled then switching to v0.2): in the situation that, for example, `A -> B -> C`, if we set B inactive, should Easer also mark C inactive or should Easer promote C as if it is directly connected on A (so making it behaves like `A -> C`)?

**Comment by renyuneyun** [comment]
Finally I decide not to guess user's intention - Easer will make the whole subtree inactive.

Added in v0.3.3 (6d7d03d).

And as always: closed for now; feel free to re-open; discussions are welcome :)
