### ISSUE TITLE
[FR] add delay

### ISSUE THREAD

**Issue by spaetz** [renyuneyun/Easer#180]
Often, if a condition is true I want to take action, but only if the condition is still true some time later. For this, it would be great to either set in the condition section or in the script section:  ' true for at least X seconds'.

My use case: I use cell ID as condition a lot, and when the phone looses connection for a second, Eg because it switches from GMS to UMTS, the condition 'leaves area' is immediately triggered. But 2 seconds later, it is in the area again, so I don't want to take any action.

**Comment by renyuneyun** [comment]
Hiya, this is actually implemented already ;p
(Well, partially... See below.)

You can find an "Event" called Timer, which you can have a delay. You can / need combine this with "chained Scripts" (by selecting "Parent"), and re-check after the delay.

Though, the current implementation of "Timer" is for longer delays, usually minutes or more. There is a plan (and an issue IIRC, but I couldn't find it now) to extend the "Timer" for shorter delays.

**Comment by spaetz** [comment]
Ahh, that is good to know. Will try it out. Not exactly intuitive UI, but well :-)...
Feel free to close this one then, if you dpn't intent to make this prettier.

**Comment by renyuneyun** [comment]
@racuna It shall be a child for this case. Though, technically, it *can* be used as a parent for other needs (if you really have).

**Comment by renyuneyun** [comment]
The Timer Event has been extended to support shorter delays (seconds) in v0.7.1 ;)

I'm closing this issue now. Feel free to reopen this issue (or open a new one if more appropriate) if otherwise.
