### ISSUE TITLE
Feature Request - Add "Record location"

### ISSUE THREAD

**Issue by Mannshoch** [renyuneyun/Easer#189]
Wi wish also as mentioned in #87 I wish the possibility to create a location by recording GSM and GPS location over a certain time.
If im Inside this named location ( connected with a recoded Tower or inside of a specific range around a/several GPS point the location should be active.

**Comment by racuna** [comment]
Yeah. Llama used to have something like this: record cells for a certain time (defined by user) then, tag the group of cell towers with a name "Cinema", "Home", "Work", etc.

Then that tag can be used in the scripts

**Comment by Mannshoch** [comment]
I know Llama, It was also my first such tool
The location tool was great. You could point a location by map and set a range for GPS and/or record a location by mobile antenna and/or by available W-Lan. In these modern days you may want create a location by Bluetooth token or NFC also. 

e.g If one of all these are available, the location "Work" is active. ... Maybe, if you record more than on indication e.g. Antenna, token, etc you may could force a scan for another indication to verify the location. Because a Mobile antenna could spread a really wide range so a second indication could narrow it a bit.

**Comment by renyuneyun** [comment]
Hi,
Do you mean the same thing as #125 ?
If so, I'm planning to add it very soon (very likely in v0.7.2).

**Comment by renyuneyun** [comment]
Done in 33492e6e (v0.7.2.3) :)
