### ISSUE TITLE
Launching apps is broken because typing / in the "App" field is not supported

### ISSUE THREAD

**Issue by xfrostbite13x** [renyuneyun/Easer#195]
Normally, almost all apps in my phone (spotify, firefox, messenger...) don't just launch using the package name. For example, Firefox launches org.mozilla.firefox/.App when i press its icon.

In Easer's profiles, launching FF by typing only org.mozilla.firefox does work, but only in this istance. Most other apps don't show anything when you remove the part after the slash (I think the / means an Activity?)  
 
The in-app activity log gives me "extra info Failed: launch_app" when it doesn't work, if that helps.

I'm unfamiliar with GitHub so bear with me please. Love your app, cheers mate.

**Comment by renyuneyun** [comment]
Hi there,
I believe you are right that the slash should mean the Activity name. But you should be able to type arbitrary character into the "package" field (at least for the two IMEs on my device). Is this related to your input method?

Though, it seems strange to me why firefox works in this way but (facebook?) messenger doesn't: they both have only one *launcher activity* (one icon in your app drawer) IIRC. I'll try to figure it out.

**Comment by xfrostbite13x** [comment]
Sorry, I worded that poorly.  
It's not that that I literally can't type a slash in the "package" field.  
The problem is that when a slash is present, the app fails to launch. Then Easer's activity log gives me the same error I mentioned initially.  

I still have the app installed on my phone but can't use it due to this problem.

**Comment by renyuneyun** [comment]
Ah, I see your point now.
I think I know where the problem is. I'll fix this soon.
