### ISSUE TITLE
TCP/UDP data transmission does not work

### ISSUE THREAD

**Issue by wrgcpp** [renyuneyun/Easer#197]
I have configured a profile with network transmission inside. 

![image](https://user-images.githubusercontent.com/6756060/49668238-580f7a00-fa7f-11e8-8b74-73ffda5e6ec6.png)
Phone is connected to my WiFi network, 192.168.0.106 is my PC. 
PC is running netcat in UDP listening mode like this: `nc -u -l -p 1488`
Profile triggering does not result to data transmission, i see nothing in my terminal window, where netcat is running. TCP transmission does not work for me too.

**Comment by wrgcpp** [comment]
Easer version is 0.7.2-ALPHA

**Comment by GregSutcliffe** [comment]
I'm seeing the same behavior - I'm trying to log events to my server, but the network transmission does not work, regardless of TCP or UDP transmission - `nc` never sees anything.
