### ISSUE TITLE
Chained scripts (with parent) doesnt work.

### ISSUE THREAD

**Issue by chrm-software** [renyuneyun/Easer#201]
Hi,
maybe I'm just not able to understand the concept, so let me explain.

I want to switch on BT while leaving the house (disconnecting from my wifi), but only Mon-Fri.

1. create condition "C:workday", with "Day of Week -> Mon...Fri"
2. create condition "C:connected_to_wifi", with "Match SSID -> My_SSID" 
3. create profile "P:outside_house_workday", with "Enable Bluetooth"
4. create script "S:is_workday" with no parent, no profile and condition "C:workday"
5. create script "S:out_workday" with parent "S:is_workday" profile "P:outside_house_workday" and inverted condition "C:connected_to_wifi

Leaving home works fine (enables BT), but on every day of week! So the AND connection to the parent script seems to be ignored.

If this is not a bug, whats the correct way to chain two conditions with an logical AND?

It would be more logical for me to add more then one condition to a script, like adding more settings in the profile configuration.

**Comment by renyuneyun** [comment]
Hi,
You are right about the intuition about the AND connection. This demonstrates a bug in Easer, and I'll look at it soon.

Based on your description, it's most likely a bug in the day-of-week condition. I'll check that in these days.

**Comment by renyuneyun** [comment]
Since there is no more activity, I'm closing this issue for now.
If this is still a thing, please feel free to re-open.
