### ISSUE TITLE
Changing name of event crashes service

### ISSUE THREAD

**Issue by Zocker1999NET** [renyuneyun/Easer#202]
After changing the name of an event, the app crashed instantly.
Restarting the app works, but it keeps crashing if I try to re-enable the service.
The reason seems to be, that a script had used this event,
but it cannot be found again, cause its name has changed.
I fixed this by reconfiguring the specific script.

However it does not seem userfriendly if the app keeps crashing after renaming something.
It would be better if you use something like an id
or change the name in each object using the renamed object.

**Comment by renyuneyun** [comment]
Hi,
I believe you are right about the problem cause. I did a lot of work trying to ensure such cases, but there could always be something I missed.
This is clearly a bug and I'll fix this soon.

**Comment by renyuneyun** [comment]
So, I made a few tests yesterday, and no crash appeared.

Could you please provide an example?

**Comment by Zocker1999NET** [comment]
It seems that it does work now, the script keeps connected to the correct event without issuing any crashes.

However, I found a similar issue with renaming a condition.
After renaming a condition, a script using the condition inside an inline event will now reference to a complete different condition. I would suggest to use IDs to link conditions to scripts if possible, this may can prevent problems with renaming.

**Comment by renyuneyun** [comment]
Done in 425c9ccd (v0.7.2.3) :)

**Comment by renyuneyun** [comment]
Using an ID would be ideal, though I'd prefer to delay that to the time when Easer switches to a better (more sophisticated) storage backend... So that's beyond the near-future targets.
