### ISSUE TITLE
Set Condition "time" as intervall

### ISSUE THREAD

**Issue by whowantsmybigdata** [renyuneyun/Easer#204]
I use "easer" mainly for setting the brightness as my phone lacks a brightness sensor and so far it works great - thanks a lot! 
My only issue: While setting a certain time as a condition to trigger a profile I'm only able to set "after" some time. This is problematic as for my case I can onlyset 60% brightness after 8 am, 40% after 5 pm and 0% after 7 pm.now when its 8 pm I get 3 conditions fulfilled at the same time and easer doesnt know which profile to choose.
Best would be beeing able to set time as "after" and "before"...
thanks in advance

Edit: Made it work with setting the times as events connected to connectivity type wifi+mobile

**Comment by renyuneyun** [comment]
Hi,
Have you ever looked at the "reversed" thing when editing a Script?

**Comment by racuna** [comment]
I have this chain of nested conditions:

Wifi connected -> Charging -> After 3am -> After 6am (reversed): Launch backup app.

But never gets triggered. It is a limit on how much nested conditions can be used?

I'm using Android P.

**Comment by renyuneyun** [comment]
@racuna It sounds like a bug. Your chain looks sensible to me.

Could you have a further investigation on which part is not activated? (And then open a new issue for this, as this is not related to the original issue.)
Currently you can check that through the activity logs inside the app. (Alternatively, I'm trying to make the Pivot page show which script is "currently" satisfied, which should appear in a release soon.)

**Comment by renyuneyun** [comment]
Since there is no more activity, I'm closing this issue for now.
If this is still a thing, please feel free to re-open.
