### ISSUE TITLE
Refactoring the way permissions and plugins could be granted/activated

### ISSUE THREAD

**Issue by edaubert** [renyuneyun/Easer#207]
I proposed a pull request about the way to manage permissions (cf https://github.com/renyuneyun/Easer/pull/206).

However I did not explain why I proposed it. Sorry about that.

My original idea was about a way to know what do what.
Currently plugins (event, operations) are not described.
Even if they are quite simple to understand, in the future the plugins could be more complicated.

For example, I have built a termux plugin which allow to run some scripts inside termux.
But, to me, this plugin needs some explanation to be used.

So I was thinking about a page which shows all the available plugins.
And for each plugin, we will be able to have some extra information.

The first one would about their requested permissions.
Currently, the permission are asked when we click on the button "grant permissions" but we don't know why.
Moreover some permissions are asked twice because multiple plugins use the same permission.

Using this specific pages will help the users to understand what plugin needs what and so allow the user to activate the plugin they want to use.
This way, there is no more multiple requests for the same permissions.

After having this information on this new page, I'd like to add some description for each plugin.

Finally I'd like to hide the plugins which dont have the requested permissions.
This way, we reduce the number of element we display.
Plus, there is no more permission requests poping during the configuration.

What do you thing about this ?

**Comment by renyuneyun** [comment]
Hi there,
I totally agree with you. A more detailed explanation about permissions will make users be in more control (which I believe is the real user-friendly).

As you may have already know from my comment in your PR, there is already a setting there in the Settings to control which plugin to enable and which not to. I think if the permission status is also listed there will be a cleaner way.


By that way, maybe the UX could be "tap to grant all permissions" (for one plugin) and "long-press to see a break-down list of explanations" (this will need a lot of work, both documentation and coding and also specifying). Luckily I already wrote a list [on the wiki](https://github.com/renyuneyun/Easer/wiki/%E6%AC%8A%E9%99%90-Permission).

**Comment by edaubert** [comment]
Ok, I don't have time currently but I will soon and I will try to make the changes and will propose something

Thanks for your feedbacks.

**Comment by renyuneyun** [comment]
Please feel free to do only one bit at a time (one PR). A skeleton would be perfectly enough and I can fill in the details.

**Comment by renyuneyun** [comment]
Closed for the discussion in #206
