### ISSUE TITLE
Is there a privacy policy statement?

### ISSUE THREAD

**Issue by HarryHeights** [renyuneyun/Easer#208]
Hi, I'm Harry, I started using the app recently. Yesterday to be precise. But, I noticed that it required too many permissions, some of which may warrant data collection. So I decided to ask about how you deal with user privacy when the app is utilized.
I'm not so skeptical about my privacy though, but I think other people might be.
If the document is unavailable, I can help create one for you. It wouldn't be a problem at all

**Comment by renyuneyun** [comment]
Hi there.
First of all: Easer won't be able to send ANY personal information through the Internet, unless you create a Script to do so. I would say, Easer is actually a "standalone software" (as in the sense of "standalone games"), so there doesn't seem to be the needs to have a privacy policy statement, right?
Actually I'm a bit skeptical on hidden information transmissions ;p

There is a [page in the wiki](https://github.com/renyuneyun/Easer/wiki/%E6%AC%8A%E9%99%90-Permission) stating which permission is used by which component. Sadly people often ignore the welcome page (which contains a link to the wiki).

But you are right about the permissions not specified clearly. #206 and #207 are trying to improve the situation. The [remote plugin mechanism](https://github.com/renyuneyun/EaserOperationPluginExample) is another way I'm currently looking at, to minimise the bundled permission requirement.

**Comment by HarryHeights** [comment]
Okay. Thanks for clarifying. I appreciate.
