### ISSUE TITLE
Apk isn't available

### ISSUE THREAD

**Issue by qirsanb** [renyuneyun/Easer#213]
Tried downloading many times from https://f-droid.org/en/packages/ryey.easer/ but it seem apk isn't available on fdroid.

**Comment by ildar** [comment]
What is that supposed to mean?
Easer (Event-driven Android automation) - https://f-droid.org/app/ryey.easer

**Comment by de-es** [comment]
F-Droid has problems with its repo atm, so APKs are currently not available (404).

**Comment by lotth** [comment]
It works today. I suggest closing this issue if it was an f-droid issue, not an easer issue.
