### ISSUE TITLE
Adding ESSID with a space in name does not work unless quoted

### ISSUE THREAD

**Issue by craftyguy** [renyuneyun/Easer#22]
When adding an ESSID with a space in the name, like 'Super Cool Wifi', does not result in any actions being taken unless the ESSID is surrounded in double quotes. This is unintuitive, and I only discovered it after trying to figure out why events were not triggering when connected/not connected to specific networks.

I suggest implementing this such that the SSID can be entered with spaces, and any quotation is handled by the app.

**Comment by renyuneyun** [comment]
That's wierd. Actually I didn't set any constraints and never used any special marks to (/for) WiFi connection names.

Not sure if there is any limits in the `XmlPullParser`. I'll try to find out.

**Comment by renyuneyun** [comment]
OK, I figured out.
Android's `WifiInfo.getSSID()` will return the name with quotation marks. I didn't see that in the beginning.

Now it can be fixed :)

**Comment by renyuneyun** [comment]
707f98825eddf6ec942ca118024506a06d1b08ca (v0.3.3.2) should have fixed this.

**Comment by craftyguy** [comment]
Awesome, thank you and nice work! :)

**Comment by craftyguy** [comment]
This appears to be resolved now, thank you!
