### ISSUE TITLE
impossible to set non empty "Reply data" in "TCP Trip" Events

### ISSUE THREAD

**Issue by stuart12** [renyuneyun/Easer#220]
hello, in Easer 0.7.4.1, is in not possible to set a non-blank *Reply data* for a *TCP Trip* Event. This is probably due to [if (check_reply && !Utils.isBlank(reply_data)) return false](https://github.com/renyuneyun/Easer/blob/28ac7f583681f111d09868a786ae4aa196db81e7/app/src/main/java/ryey/easer/plugins/event/tcp_trip/TcpTripEventData.java). I'd guess that the *!* is a typo but why check the *reply_data* at all? I do not see any reason for any restrictions on the *Reply data*.  It can be empty or not (except at the moment if it is empty Easer crashes #219)

The message when I click on *SAVE* with *Check reply" selected and a non-empty *Reply data* is *Prevented saving data with invalid field(s). Please recheck your choices / inputs.*

**Comment by renyuneyun** [comment]
You are right. The field should not be checked at all.
I'll fix this in the next release.

**Comment by renyuneyun** [comment]
Forget to mention: this bug should have been fixed with v0.7.6.

I'm closing this issue. Feel free to reopen this issue if not.
