### ISSUE TITLE
( BUG ) Found in Easer app The application crashes when I try to open the dynamic link option

### ISSUE THREAD

**Issue by saraji-ali** [renyuneyun/Easer#224]
# Project Information

* Repository: https://github.com/renyuneyun/Easer
* Project Name: Easer  

# Expected behavior
I was expected that when I click on the dynamic link option, further options will appear and I can add the dynamic link there.

# Actual behavior

After opening the application, I go to the script tab and click on the plus button and then I click the dynamic link icon, the application crashes.

# How to reproduce

1- open the application 
2- Click the three horizontal line at the top left
3-Select the script option
4- click on Plus button
5-Below the profile you will see 3 options   inline event, Predefined event, and use condition,
6-select  Predefined event
7- Click on the dynamic link icon
8- see the bug

* Browser/App version:  v0.7.5
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190515_150831](https://user-images.githubusercontent.com/50115498/57769565-15536d00-76c3-11e9-8a17-802d0f9dfd4d.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime( 9017): FATAL EXCEPTION: AsyncTask #1

E/AndroidRuntime( 9017): Process: ryey.easer, PID: 9017

E/AndroidRuntime( 9017): java.lang.RuntimeException: An error occured while executing doInBackground()

E/AndroidRuntime( 9017): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)

E/AndroidRuntime( 9017): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)

E/AndroidRuntime( 9017): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)

E/AndroidRuntime( 9017): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)

E/AndroidRuntime( 9017): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)

E/AndroidRuntime( 9017): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

E/AndroidRuntime( 9017): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

E/AndroidRuntime( 9017): 	at java.lang.Thread.run(Thread.java:818)

E/AndroidRuntime( 9017): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

E/AndroidRuntime( 9017): 	at ryey.easer.d.d.g$b.a()

E/AndroidRuntime( 9017): 	at ryey.easer.d.d.g$b.doInBackground()

E/AndroidRuntime( 9017): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)

E/AndroidRuntime( 9017): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

E/AndroidRuntime( 9017): 	... 4 more
</code></pre>

**Comment by renyuneyun** [comment]
Ah, thanks for reporting. That's a UI problem.

In principle, Dynamics only makes sense if you have a trigger (i.e. Event or Condition) and is functioning on the Profile. If you have an Event or Condition selected, the problem will go away.

But yes, the UI needs to reflect that.
