### ISSUE TITLE
( BUG ) Found in Easer app After going to the event tab, the application crashes when I click on the call location icon

### ISSUE THREAD

**Issue by saraji-ali** [renyuneyun/Easer#225]
# Project Information

* Repository: https://github.com/renyuneyun/Easer
* Project Name: Easer
 

# Expected behavior

After going to the event tab I was Expected that  when I click on the location icon, my location will appear in the google map

# Actual behavior

 After going to the event tab, I set the condition event and then set the time, and the date and then I connect the WiFi and when I click the call Location icon, the application is crashed.

# How to reproduce

1- open the application
2- Click the three horizontal line at the top left
3- select the event tab 
4- goto call location option and click on Call Location icon
5- see bug

* Browser/App version: v0.7.5
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190515_151037](https://user-images.githubusercontent.com/50115498/57770604-8c8a0080-76c5-11e9-9149-ea82f93179f7.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime( 9017): FATAL EXCEPTION: AsyncTask #1

E/AndroidRuntime( 9017): Process: ryey.easer, PID: 9017

E/AndroidRuntime( 9017): java.lang.RuntimeException: An error occured while executing doInBackground()

E/AndroidRuntime( 9017): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)

E/AndroidRuntime( 9017): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)

E/AndroidRuntime( 9017): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)

E/AndroidRuntime( 9017): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)

E/AndroidRuntime( 9017): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)

E/AndroidRuntime( 9017): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

E/AndroidRuntime( 9017): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

E/AndroidRuntime( 9017): 	at java.lang.Thread.run(Thread.java:818)

E/AndroidRuntime( 9017): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

E/AndroidRuntime( 9017): 	at ryey.easer.d.d.g$b.a()

E/AndroidRuntime( 9017): 	at ryey.easer.d.d.g$b.doInBackground()

E/AndroidRuntime( 9017): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)

E/AndroidRuntime( 9017): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

E/AndroidRuntime( 9017): 	... 4 more
</code></pre>

**Comment by renyuneyun** [comment]
So, is this a duplication of #216 ?

**Comment by facebook-786** [comment]
okay sir

**Comment by renyuneyun** [comment]
Since there is no more activity, I'm closing this issue for now.
If this is still a thing, please feel free to re-open.
