### ISSUE TITLE
Feature request: Event triggered by tapping widgets

### ISSUE THREAD

**Issue by nicolas-raoul** [renyuneyun/Easer#229]
Sometimes I want to trigger some operations at will, not based on a particular event.

It would be great if it could be done by placing widgets, and then pushing them.

The app "MacroDroid" has this feature.

Ideally I could put a name under the widget (for instance "study" or "clubbing"), unlike MacroDroid which uses a finite set of colors.

Thanks a lot!

**Comment by renyuneyun** [comment]
Thanks for proposing. This indeed seems sensible. I was thinking about this too actually.

Similar to #227, I will investigate more on the exact behaviour of widgets, and try to figure out how to implement that.

**Comment by renyuneyun** [comment]
This is implemented in v0.7.8 (currently v0.7.8-beta is published, and should appear in f-droid in a few days). Hopefully no much bug reports and v0.7.8 can be moved to stable (well, not that stable, but without big problems).

**Comment by renyuneyun** [comment]
I'm closing this because of long inactivity, so I'm assuming a version solving this should have been working. Please open a new issue if otherwise, and link to this issue.
