### ISSUE TITLE
Add event for Bluetooth connection to specific device

### ISSUE THREAD

**Issue by craftyguy** [renyuneyun/Easer#23]
This request is to add a new event for when Bluetooth is connected to a specific device. This would allow, for example, starting music when the phone connects to Bluetooth speakers.

**Comment by renyuneyun** [comment]
v0.3.5 is in f-droid repo, and seems to do the right job. (Well... the enumator doesn't support bluetooth so I didn't really tested it there :P)

Also v0.3.5 provided the ability to import and export profiles and events, so I can safely test on my phone from here on.

**Comment by craftyguy** [comment]
Great, thank you! It seems to work for me too!
