### ISSUE TITLE
Request: Update Easer 0.7.7.x Beta (F-Droid)

### ISSUE THREAD

**Issue by twikedk** [renyuneyun/Easer#235]
Maybe it could be a good idea to update the Beta version on f-droid? That would at least help me out to do some 0.7.7.x testing without breaking the running and working 0.7.6.2 I'm using now.

**Comment by renyuneyun** [comment]
Actually there is an update at the time of asking: v0.7.7.6-beta.
Though, f-droid has some delays, and the version appeared late (but it's there now).

I'm pushing v0.7.8-beta today too.


I think it's fine to close this issue?
