### ISSUE TITLE
Missing unit of parameter "Cool down time" in options

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#244]
I'm missing unit of the parameter "Cool down time".
What's the unit of the entered value? Milliseconds? Seconds? Minutes?

I suggest to give that information in the parameter's short description, like this:
"Minimal interval between two triggers of the same event in seconds".

I'm currently using Easer 0.7.8-beta.

**Comment by renyuneyun** [comment]
Quick version: seconds.

You are right, it should be added. A few people talked about this already.

**Comment by just-Nob** [comment]
Is added in version 0.7.8-beta3.
