### ISSUE TITLE
Feature: Allow HTTP requests as profiles.

### ISSUE THREAD

**Issue by xylo** [renyuneyun/Easer#247]
There is already support for network transmissions.  But since nowadays most APIs are HTTP based it would be nice to have an option to send HTTP requests easily.

**Comment by renyuneyun** [comment]
Good proposal.

The only thing I'm considering is: should this be implemented as an internal Operation or a plugin? (Because, bascially, what about HTTPS?)

**Comment by xylo** [comment]
For me this is just a specialization of the "Network transmission" function.  I would probably implement it the same why this function is implemented.  But I don't know the concept behind Easer, neither I've ever looked into the code.  Maybe I will at some point. ;-)

And yes.  HTTPS should be included as well I think.  For me this is pretty much the same, so I did not explicitly mention it.  But HTTPS is even more important in this regard, but should not make much of a difference.  Maybe an option for skipping the certificate check would be interesting as well for HTTPS user.  But that's the only main difference I can think off.

**Comment by xylo** [comment]
I started working on this.  Pull request is probably coming today.

**Comment by renyuneyun** [comment]
So basically, I think this issue can be closed, since HTTP Operation and the relevant Dynamics are both in the master branch already?

**Comment by xylo** [comment]
Thanks for merging.
