### ISSUE TITLE
Dynamics for "SMS Sender" and "SMS Content" not working

### ISSUE THREAD

**Issue by wei3er** [renyuneyun/Easer#250]
The Dynamics for "SMS Sender" and "SMS Content" are not replacing the associated placeholder (e.g. in the  "Send SMS" operation).

This bug was found on Google Pixel (sailfish), Android 9,  Release 0.7.7.7

**Comment by wei3er** [comment]
The bug also occurs on Oneplus 6 (enchilada), Android 9, Release 0.7.7.7

**Comment by renyuneyun** [comment]
Thanks for reporting. I'll investigate soon.
