### ISSUE TITLE
Day of the week needs manual refresh

### ISSUE THREAD

**Issue by racuna** [renyuneyun/Easer#252]
I have different sound profiles for workdays and weekends. After installing version 0.7.7.7 I can see on the Pivot that weekends still have green lights on their boxes today (monday at 11am), and workday condition box is in red.

After taping the refresh button, the workday profile turns green, and workday sound profile is activated correctly. But It needs to be refreshed manually.

**Comment by renyuneyun** [comment]
Thanks for reporting!
I'll try to figure out soon.

(Maybe this is also related to another issue...?)

**Comment by racuna** [comment]
Thanks, but pivot still thinks it is weekend (green light), and the history does not show any day of the week check either.

**Comment by renyuneyun** [comment]
Sorry for not seeing the further feedback...
Is this problem still valid now?
