### ISSUE TITLE
Display Error wegen switching to "Data" Section

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#254]
When switching from "Outline" or "Pivot" to "Data", the headline in the upper left corner (near to the menu button) isn't actualized to "Data" but stays displaying the former status ("Outline"/"Pivot").

I'm currently using Easer 0.7.8-beta2, running on 64 bit arm, Android Oreo 8.1.

**Comment by renyuneyun** [comment]
Thanks for reporting :)

**Comment by just-Nob** [comment]
Seems to be fixed in 0.7.8-beta3.
