### ISSUE TITLE
"Pivot" overview too small in case of more script threads

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#259]
I really appreciate the "pivot" graph which is very intuitive for getting an overview of the existing scripts as well as in case of debugging (due to its status indicator).

But if you have more than two or three script threads, the zoom is insufficient, i.e. it's not possible to zoom in until the labels are legible (the characters are much too small).

**Comment by renyuneyun** [comment]
Hmm, do you mean the text is still not readable even if you have zoomed in?

That's good to know. I'll see if the [upstream](https://github.com/Team-Blox/GraphView) already knows this issue or not.

**Comment by just-Nob** [comment]
Yes, that's what I mean.
Even when zooming in as much as possible (maximum zoom), the text is too small.

**Comment by just-Nob** [comment]
This issue is still valid on final version 0.7.8.
Unfortunately, I'm not allowed to re-open that issue, because I'm not the member that closed the issue. 😒

**Comment by just-Nob** [comment]
Here's an example, maximum zoom-in:
![Screenshot_20190917-233155](https://user-images.githubusercontent.com/25401767/65081311-a5702e80-d9a3-11e9-9f55-cbea046e64ea.png)

**Comment by just-Nob** [comment]
It's ok in v.7.8.2-beta. 👍🏼
