### ISSUE TITLE
Add a button to run/test profile

### ISSUE THREAD

**Issue by xylo** [renyuneyun/Easer#263]
When I create a profile I usually want to test it immediately to ensure that the profile works before I go on with events and scripts.

It would be nice to have a test button on each profile page.

**Comment by just-Nob** [comment]
Hi @xylo ,

interesting idea, but I don't think that's a bug (concerning the label you assigned to that issue). 😉

Anyway, I created a workaround to fulfill that need:
I just created an event with a widget which I named "Test Widget" and placed a corresponding widget on my homescreen (don't choose the "Easer" widget but the "WidgetEvent Widget" to place!).
Then I created a "profile test" script with the "Test Widget" event as condition.
Now you can select every profile you want to be executed by the script. Just save the script after your choice and test the profile by a trap on the widget! 🙂

Nevertheless, I admit a "test profile" button to be a little more concurrent. 😉

**Comment by renyuneyun** [comment]
Actually this is already there: try long-press on the desired Profile and you will see the option there.

**Comment by just-Nob** [comment]
Cool - it works! 🥳

**Comment by xylo** [comment]
Thanks for the hint, @renyuneyun!

**Comment by xylo** [comment]
@renyuneyun Is it possible to create tickets that are not automatically labeled with `bug`?  Unfortunately, normal users cannot change the labels.  So I could not remove it.
