### ISSUE TITLE
Bug: Wrong (inverted) polarity of condition "Headset"

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#268]
**Just do the following (steps to reproduce):**
1) Create a condition of type "Headset" with "Headset state = plugged in" & "With microphone = any". You may call it "Headset plugged in". 
2) Create a script. Reference the condition that you created before (condition "Headset plugged in"). Assign any profile to it, e.g. a notification. You may call that script "Headset testing".
3) Switch _Easer_ to show the "Activity History".
4) Plug in a headset (I used one without microphone). Android's "headset" icon appears in the status bar, whereas _Easer's_ "Activity History" shows "script: Headset testing" / "Status: Unsatisfied". **(Expected behavior: Status = satisfied!)**
5) Plug out the headset. Android's "headset" icon disappears, whereas _Easer's_ "Activity History" shows "script: Headset testing" / "Status: Satisfied". **(Expected behavior: Status = unsatisfied!)**
_Also interesting: When no profile is assigned to the script "Headset testing", no further history entry is added when plugging it the headset!_

If this is wrong for both plugged headsets as well as for Bluetooth headsets, that probably may be the root cause for issue #243.

I'm currently using Easer 0.7.8-beta3, running on 64 bit arm, Android Oreo 8.1.

**Comment by sphh** [comment]
I tried it with BT headset and on my phone it works as I would expect it.

**Comment by renyuneyun** [comment]
I think you are right.
There was an issue of the Headset Condition (due to the data after merging that to USource), and that's fixed in 94f39a2.

I'll publish a version recently if possible. Hope this fixes the issue.

(It may automatically close this issue. Please feel free to re-open it.)
