### ISSUE TITLE
Easer does not check the conditions 

### ISSUE THREAD

**Issue by halbesbrot** [renyuneyun/Easer#273]
Hello!

Easer runs in my foreground all the time and has all permissions.

Nevertheless it does almost nothing automatically. It only checks the conditions (e.g. time or cell location) when I press the sync-button and then the profiles are executed correctly.

On events (e.g. receiving an SMS) Easer reacts correctly.

I have Blackberry key2 LE with Android 8.1.
I have/had this problem with Easer beta 0.7.8-BETA3 and Easer 0.7.8.

**Comment by halbesbrot** [comment]
Error found. The error is me.

Easer only reacts to events and not to conditions. Sorry for the issue.

**Comment by renyuneyun** [comment]
Glad you figured it out.

If you choose "Event", then Easer checks for events. If you choose "Condition", then Easer checks for conditions.
