### ISSUE TITLE
[FR]: Edit the parameters of a widget afterwards from within Easer

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#275]
It would be great to have the possibility to edit the parameters (currently only designator/text and tag) of any of Easer's widgets.
That would be a big relief in case of typos, for example. Currently, one have to delete the old widget and to add a new one with the corrected values.
In addition, you currently have no chance to check the entered values of a widget, for example for typing errors in the TAG.

All that would be possible in case of an editing function of the widgets' values inside Easer.
To implement this, an additional tab "Widgets" could be added in the "Data" section next to "Scripts", "Conditions", "Events" and "Profiles".
The different widgets could be identified by their designators (currently simply called "text" when adding a new widget, which is on fact the widgets designator to be displayed).
This would mean that it should be forbidden to create two widgets with the same name (designator) - which makes no sense anyway, because otherwise the widgets could not (currently) be distinguished on the home screen.

Later this feature could also be used, for example, to edit further, perhaps more complex features later on; I think here especially of an icon that could be assigned to the widget for pimping the widget's appearance. 😁

**Comment by just-Nob** [comment]
To have a better idea of what I'm talking about, you may have a look at "Todo Agenda", which is available at the F-Droid so store, for example (https://f-droid.org/en/packages/com.plusonelabs.calendar/).
"Todo Agenda" is a pure calendar widget app to display upcoming calendar dates.

Multiple widgets with totally different settings (choice of calendars to be displayed, appearance, widget name for better identification...) could be placed on the homescreen.

If you open "Todo Agenda" from the device's so launcher, the 'only' function it offers is to show all widgets currently placed on the device's homescreen and - if one of them is chosen - to give the user the ability to edit all of its parameters!

**Comment by renyuneyun** [comment]
Interesting, I thought it was only (the launcher of) my ROM (OxygenOS) which can't configure the widget afterwards.
I remember it used to be possible to drag the widget and then the launcher will display a "configure" button (area) next to "remove" button (area), when I was still using my earlier phone (on Android 4.x).

I'll wait to gather some more information, to see if this is the launcher's problem.

**Comment by just-Nob** [comment]
Additional information referring to my launcher: I'm currently using OpenLauncher (https://f-droid.org/en/packages/com.benny.openlauncher/).
