### ISSUE TITLE
[FR]: different sorting types (= order of appearance) for data elements

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#279]
The different types of data elements (scripts, events, conditions, profiles) should have different kinds of sorting (for each in its kind of data element) .
Here are some suggestions:
* Timestamp of creation / editing (the current display order, I guess?),
* alphabetically by name,
* excepted scripts: kind of event/condition/profile...

Each sorting could also be switched between ascending/descending.

**Comment by eandersons** [comment]
This would be useful as sorting (for example, alphabetically) would make it much easier to spot the necessary item when a list of data elements is quite long.

One addition to the feature request: sorting should be applied to dropdown and popup selects as well.

**Comment by renyuneyun** [comment]
Indeed, I would consider this a duplication of #181.
I'll mark close this one, in favour of the earlier one.
