### ISSUE TITLE
[Bug]: "Timer" Event for 'longer time' incorrectly displayed when being edited again

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#280]
If you set up a "long time timer event", i.e. you choose "Longer Time" and enter a longer time duration (e.g. 15 minutes), save the event and reopen it again, you will find the event set to "Shorter Time" with the duration left empty.

I guess that this is only a visual bug, because of you choose "Longer Time" again, the chosen period (15 minutes in my example) is visible again and doesn't need to be entered again.
Anyway, I'm not really sure about the function not being influenced by that bug.

**Comment by renyuneyun** [comment]
Thanks for reporting.

I believe this is a UI bug only. I have found it and will fix this.

**Comment by renyuneyun** [comment]
85f8c3d should fix this issue. I just published v0.7.8.3-beta2 which contains this commit.

Please have a try after it appears in the repo, and report back (hopefully close).

**Comment by just-Nob** [comment]
For sure, I'll do.
If it's fixed, I'm going to close the issue, otherwise I will report here.

**Comment by just-Nob** [comment]
Seems to be solved in Easer 0.7.8.3-beta2, so I'm closing that issue.
