### ISSUE TITLE
[Bug]: "Time" condition isn't correctly triggered or evaluated

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#281]
**I recognized this bug when I tried to do the following:**
I wanted to switch the phone's ringer mode _mainly(!)_ dependent on day time:
1. In the morning, the phone should stay in "DND" as long as I'm not awaken. The phone should ascertain my awakening by being connected to the internet for a minimum of 15 minutes _after_ 4:30 a.m. (to understand that requirement, one have to know that I switch my phone to flight mode during the night / before I fall asleep - but it may also be that I only just want to check an important mail or something like that in the early morning, but want to continue sleeping thereafter; that's why it needs the 15-minutes-delay). If that is fulfilled, the ringer mode is intended to switch to "normal".
2. In the early evening (8:00 p.m.), the phone is intended to switch it's ringer mode to "vibrate", for not waking up my little kids in case of an incoming call/message/whatever.
3. In the late evening (11:00 p.m.), the ringer mode should switch to "DND" (only alarms to disturb), because I don't want to be disturbed by anything anymore.

.

**To achieve that behavior, I've done the following:**

_**Profiles:**_
I added three profiles, each with not only the ringer mode to switch, but also a "Send Notification" action, giving me the info that a certain profile is activated as well as date and time of the activation by using the "dynamics" (on conjunction with the calling scripts, for sure):
1. "Day" → Ringer mode to "normal".
2. "Early evening" → Ringer mode to "vibrate".
3. "Late evening" → Ringer mode to "DND"

_**Conditions & events:**_
I used time _conditions_ instead of _events_ to ensure that the ringer mode switches to the desired ringer mode most certainly, even in some unexpected situations, e.g. if the phone's battery ran empty during the day (when ringer mode was set to "normal") and was switched on again maybe at early evening (let's say 9:15 p.m.) when being recharged. If the profile switching was programmed to change on time _events_, the 8:00 p.m. 'moment' would have been missed, the ringing mode sucks on "normal", and if a call comes in... - **bam!**: children are woken up!
So I'm using three timing conditions, as well as one condition for the "online status" and one timer event:
1. "Time" condition "after 4:30 a.m.".
2. "Time" condition "after 8:00 p.m.".
3. "Time" condition "after 11:00 p.m.".
4. "Connectivity type" condition "not connected".
5. "Timer" event "Longer time = 15 minutes (inexact), one time".

_**Script branches / chains:**_
The "late evening script 'branch' is the simplest, because it's only a single script:
- Condition "after 11:00 p.m." fulfilled? → activate profile "DND"!

The next script branch to describe is the one for the early evening; first I have to check if it's no late evening, then if it's early evening:
- Condition "after 11:00 p.m." **not** fulfilled (via "reverse scenario") → condition "after 8:00 p.m." fulfilled? → activate profile "vibrate"!

The script branch to switch the ringer mode to "normal" in the morning is the most complex of these three - initially, Easer has to check if it's no (early) evening, then if it's already late enough to potentially wake/stand up; of so, Easer is waiting for a data connection and starts a timer for a quarter of an hour, to ensure that short moments being online in the very early morning are not evaluated as being up early. If the 15 minutes of the timer elapsed, the profile finally is intended to be switched to "normal":
- Condition "after 8:00 p.m." **not** fulfilled (via "reverse scenario"? → condition "after 4:30 a.m." fulfilled? → condition "not connected" **not** fulfilled (via "reverse scenario")? → "Timer" event (15 minutes, not repeatable when satisfied) fulfilled? → activate profile "normal"!

.
**What's the unexpected behavior?**
It seems to me that the triggers for the _time conditions_ are missing.
_An example:_
Every evening, a couple of minutes past eight (I'm talking about 15, 20 minutes or even more!), the ringer mode should be switched to "vibrate" by its corresponding profile, but it's still "normal" mode.
I have to indicators telling me that the expected "early evening" profile wasn't activated:
- There was no notification (just remember: I added a notification to every of the the profiles!).
- A look on the pivot graph reveals that all scripts based on the "after 8:00 p.m." condition are stuck to the "not valid/activated/fulfilled" status, i.e. they still have a red "status LED" (but should have a green one).

That situation could easily be solved by opening the corresponding _condition_ ("after 8:00 p.m.") and saving it (without changing its content!).
The ringer mode immediately turns into "vibrate" mode (which can be seen by the little "vibration" icon in the status bar) and the profile's notification is displayed.

Another thing I'm a little astonished at is the fact that then the notification is displayed multiple times in sequence, all with the same time stamp, i.e. the script is called multiple times. I noticed that it was the times, but I'm not sure about whether it's fixed or may change from time to time.

I also noticed that the "normal" profile and to be called sometimes during the day - some notifications were displayed. Even here, it seems as if the script was called multiple times (i.e. with a consistent time stamp). Unfortunately, it was not yet possible for me to discover a rule under which conditions the scripts will be executed again.

I'm currently using Easer 0.7.8.3-beta, running on a rooted device with 64 bit arm and Android Oreo 8.1.

**Comment by renyuneyun** [comment]
Thanks for reporting this with a such detailed explanation.
This indeed seems to be a bug. Your Scripts seem correct to me.

Although there could be some differences to the exact timing, but 15 min is longer than expected.

I'll investigate if I have time. Hope to fix this in v0.7.9 or v0.8.

**Comment by just-Nob** [comment]
Would it be helpful for you if I added the exported scripts/data?

**Comment by just-Nob** [comment]
With version 0.7.8.3-beta2, something changed in behavior:

In original issue description, I mentioned that I only have to save the time condition that failed to "retrigger" it and make the corresponding scripts working correctly.
That behavior seems to be gone in version 0.7.8.3-beta2, so I currently don't know any way to make these scripts correctly working.

**Comment by just-Nob** [comment]
This bug seems to be fixed in Easer 0.7.9-beta, so I'm going to close this issue.


Anyway, there seems to be a new bug in that version of Easer, which may be cohered with this issue.
However, because this is a new bug/behaviour, I opened the new issue #285 and described it there.

**Comment by renyuneyun** [comment]
Yes, I forgot to mention. There was a general problem related to Time, Date and Day-of-week Condition, and fixed in the v0.7.9-beta (5784d768, more precisely).
