### ISSUE TITLE
[FR]: Switch to disable/enable scripts

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#283]
It would be nice to have the possibility of temporarily disabling a script.

There are multiple use cases for that:
- A script shall not be executed for a dedicated time, e.g. the phone usually it's muted by a script in the evening, but shouldn't be muted on a dedicated evening when being out for a party.
- A script not running correctly shall be muted because there's currently no time for debugging (and its better to don't have it running than getting unexpected results).
- For test purposes, e.g. of one don't know which script of a bunch of scripts is working wrong.
- ...

**Comment by renyuneyun** [comment]
Well, actually there is already such a thing.

Open / Edit a Script, type the three dot menu, and you'll see a checkbox called "active".

Don't forget to save in the end ;p

**Comment by just-Nob** [comment]
Hi @renyuneyun ,

indeed, you're right - that's what I was looking for!
For some reasons (that I'm currently don't know anymore), I was mainly searching for that on the script's "main level", i.e. in the script data section, where I tried things like long pressing the scripts to deactivate.
I also had a look inside the "script editing" view, but hadn't the idea to open the menu... - no idea why I hadn't that idea! ;) 

It's also helpful that a disabled script is greyed out in the script's "main level data area" as well as in the Pivot view - really nice!
Thanks for that!

So I'm going to close this issue.
