### ISSUE TITLE
Explanation of new feature "multiple predecessors for a script"

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#288]
Hi @renyuneyun,

I recognized the new feature to choose multiple predecessors per script instead of only one.
I guess that this is equivalent to a "logical OR" (becausea "logical AND" is still realized by chaining some scripts / building up a branch of of them), i.e. at least one precessor has to be fulfilled/true to trigger the script concerned with the multiple predecessors.

I think it's a good idea to add a short comment ("logical ORed" / "at least one have to be fulfilled" or something like that) in the multiple choice dialog's headline to clarify that to the user.

**Comment by renyuneyun** [comment]
Yes, it represents the OR operator.

I'll think about adding it as a prompt (alert dialog, possibly). But it may not be very important currently.
(But the first-launch information part should be updated anyway.)

**Comment by renyuneyun** [comment]
By the way, #287 pointed out f-droid failed to build this version, and I also didn't see it in f-droid. Did you get it from f-droid or you build it yourself?
(There is no harm in doing so. I just want to figure out what actually happened in f-droid repo.)

**Comment by just-Nob** [comment]
I'm currently using Easer 0.7.9-beta from F-Droid repo.
I like to start Android programming, but up to now, I haven't had the time to start this spare time project. Anyway, it might be a good idea to set up the development environment and to compile given projects like Easer.

**Comment by just-Nob** [comment]
To update the first launch screen information is a good idea, I think.

**Comment by renyuneyun** [comment]
I think this issue can be closed because of inactivity?

**Comment by just-Nob** [comment]
In the 3rd screen of the welcome massage, I suggest to supplement the sentence "Between beaches, OR logic is performed." by "This also includes branches that run together in one script (see the 'multiple predecessors' feature)." out something similar.
