### ISSUE TITLE
[Graphical Bug]: left column with designators in "script editing" dialogue shrinks/diapers in case of too many  predecessors

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#289]
As written in the issues headline, the left column with the designators shrinks and finally diapers if there are plenty of predecessors chosen in the script editing dialogue.

**Comment by renyuneyun** [comment]
Hmm, I think it's actually the same reason as #276 , as a result of using table layout (incorrectly?).

Anyway, I'll fix it if I have time.

**Comment by just-Nob** [comment]
Yes, you're right - I think the same. ;)
Ok, next time I'm going to supplement the open issue - sorry for that.

**Comment by renyuneyun** [comment]
I believe v0.8-pre-beta should solve this issue. Please have a try when it appears :)

**Comment by just-Nob** [comment]
I tried it in v. 0.8-pre-beta2, and with the "one-line-per-predecessor"-approach, it seems to be fixed.

Anyway, if there's a long script name in the list of predecessors, the name is cut on the screens right border, but that is ok for me: If one taps on the list's entries, the multiple choice dialogue appears where every script name is shown completely (by using word wrap).

So I'm going to close this issue.
