### ISSUE TITLE
"Wifi connection" question

### ISSUE THREAD

**Issue by hkemal** [renyuneyun/Easer#296]
I have the latest version of Easer from F-Droid running on LineageOS 16 without Play Service and with Location turned off.
When I use the Condition "Wifi connection" and start the Scan, it newer finishes and gives me the name of the Wifi it is connected to.
Why is this?

Regards
Kemal

**Comment by renyuneyun** [comment]
Hi there, could you please check if you have "read device location (coarse)" permission enabled for Easer?

**Comment by ildar** [comment]
Guess this is the solution.
But generally this is not right: "Plugins" page should give users a hint
that Location permission is required for Wi-Fi and BT things to work.

**Comment by hkemal** [comment]
Hi,

I do not have this permission at all. Only thing with location is Cell Location. If I give Easer the Location permission and turn Location services on, it can scan and recognize mobile cell I am connencted to. But on wifi, it now just returns an empty list.
Is it at all possible to read the wifi connection name without location services turned off?

Am 22. Dezember 2019 22:40:06 MEZ schrieb Rui Zhao <notifications@github.com>:
>Hi there, could you please check if you have "read device location
>(coarse)" permission enabled for Easer?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/renyuneyun/Easer/issues/296#issuecomment-568305019

-- 
Kemal Hajvazovic
E: kemal@mailbox.org
M: +491628231843

**Comment by ildar** [comment]
>
>
> Is it at all possible to read the wifi connection name without location
> services turned off?
>
I just tried. You seem to need both Location permission in app and Location
services on your device turned ON.

**Comment by renyuneyun** [comment]
@hkemal Well, unfortunately, not any more.
Google decided to classify WiFi hotspots as a way of identifying user locations (which some people / companies do). So from a certain version on (between 5 - 7, I think), you have to have this enabled to make an app read WiFi hotspots nearby.

**Comment by stuart12** [comment]
[WiFiAnalyzer 2.0.8](https://f-droid.org/en/packages/com.vrem.wifianalyzer/) is able to get the list of WiFi access points once the Location Service is turned on (it asks me to turn this service on).

Easer never finished its "Waiting for WiFi scan result". I do have the message "Some skills no NOT have sufficient permissions". The list is long and difficult to understand.  Could you perhaps sort the list so it is easy to find elements.  What do the white tick on a pink box mean and white tick on a grey box mean?

Under "Condition" I have "Cell Location" with a red cross. You ask about "read device location (coarse)".  I cannot see this in the list in the Easer settings page.  When I use the Android "App permissions" page I see that Easer does not have the "Location" permission.  I gave it "Location" permission and now the "Cell Location" line in Easer has a green tick.  And I can now select a WiFi network in "Edit Condition" in Easer. If I turn Location off neither Easer nor WiFiAnalyzer can get the list of networks.  Is "Cell Location" the same as "Location" for Android? Perhaps "Cell Location" should be renamed as "Location" and "WiFi Connection" could give show a message when "Location" is not on and allowed (as WiFiAnalayser does).

I will normally have Location turned off so the "WiFi Connection" condition is not useful for me. When I'm on my home network my DHCP server always gives the same IPv4 address to my phone. Could you add a condition on the phone's IPv4 address?

**Comment by renyuneyun** [comment]
@stuart12 The "Location" in Android means all measures of locations, including (but potentially not limited to) GPS (or similar), cellular towers / base stations and WiFi hotspot.
The "Cell Location" is only one part of all these things: the cellular towers / base stations. There is actually a new Condition and Event for GPS in v0.8 (beta).

For the IP address feature request, could you please open a new issue (don't use the "bug" template), so we can keep track of it there?

For the legend of the skills page (popped up after clicking "unsatisfied permissions"), I'm thinking of implementing it (after switching the `PreferenceFragment` (and everything related) to the AndroidX library), but am really short of time... Feel free to open a feature request issue for this. (And I remember there are discussion(s) in other issue(s) also mentioning this.)
