### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by mueller-ma** [renyuneyun/Easer#3]
Hi,

I have created a profile with bluetooth on and maximum brightness. Then I created an event, selected the profilem checked the clock button and entered a time. When this time has come, nothing happend. Outline was running. Did I miss something?

**Comment by renyuneyun** [comment]
Easer uses the Android system-level notification mechanism to listen for time events, and that mechanism is said to be usually inexact (for battery concern). Therefore, the event will be triggered shortly after that time - the greatest latent I observed is 3 minutes. 

By the way, each "event" takes exactly one item (either data, time, location or so). Don't be misguided by the checkboxs (they are remnants of the previous framework of Easer, and that will be solved in the near future).

I should really notify users about this, maybe in a future version or in the README file.

The next version will include a display in the outline page to show what, when and why the last profile is loaded, which may be useful to address issues of delay / latency.

**Comment by mueller-ma** [comment]
Do I have to restart the app under "Outline"? Or press the FAB?

**Comment by renyuneyun** [comment]
Hmm, it shouldn't crash... Anyway, I'll stop Easer from saving incorrect events and/or profiles in the near future. (Actually, I thought this function should already be there...)
For now, if you can use adb shell (or any adb GUI tools, or you have root privilege), you can navigate to `/data/data/ryey.easer/event/` and remove the incorrect one; or you could remove all data by using 'clear data' (from system-level app settings).

What does you mean by saying "have to restart"? The FAB means "reload" all profiles and events, though it doesn't seem to be needed at all; to restart the **service**, you could only `stop` then `start`. There is nothing other than UI and the only service, so you can safely terminate the app by any ways you like.

**Comment by renyuneyun** [comment]
20b9868 (v0.2.5.1) should have solved this problem (which checks the validity of the new event and profile).
0aad57a (v0.2.5.2) will remove your accidentally saved broken events / profiles when saving a new one with the same name.

I'll leave this issue open for now, until you have the chance to try the new version (after f-droid has them in repo).

**Comment by mueller-ma** [comment]
Yes
