### ISSUE TITLE
Call plugin doesn't store phone number

### ISSUE THREAD

**Issue by shieldwed** [renyuneyun/Easer#300]
**Describe the bug**
When entering a phone number with the call event plugin saving the event, the phone number won't be stored. Moreover doing an import with a call event which has a number set and then converting the data wipes it away as well.

**To Reproduce**
1. Go to `Data` and the choose the tab `EVENT`
2. Add a new event with any title
3. Choose the `Call` event
4. Entere a phone number
5. Save
6. Open the just created event once again and see that it is empty

**Expected behavior**
The phone number shall be saved and used to filter calls for this event

**Error log:**
No error log is generated

**Extra phone info (please complete the following information):**
 - Model: Nokia 8.1 (TA-1119 hardware version 3.1)
 - OS: Android 10 (Build number `00WW_4_15B_SP02`, Patch level `November 1, 2019`, Kernel version `4.9.179-perf+ 
#1 Wed Nov 20 11:39:36 CST 2019`)

**Additional context**
I suspect the following file contains an inverted logic:

https://github.com/renyuneyun/Easer/blob/560935c72ae2fd19971f5d43d038d9b18c00380f/app/src/main/java/ryey/easer/skills/usource/call/CallUSourceData.java#L120

This should probably changed as follows:

```diff
diff --git a/app/src/main/java/ryey/easer/skills/usource/call/CallUSourceData.java b/app/src/main/java/ryey/easer/skills/usource/call/CallUSourceData.java
index c6316e82..708827a5 100644
--- a/app/src/main/java/ryey/easer/skills/usource/call/CallUSourceData.java
+++ b/app/src/main/java/ryey/easer/skills/usource/call/CallUSourceData.java
@@ -117,7 +117,7 @@ public class CallUSourceData implements USourceData {
                         }
                         jsonObject.put(K_STATE, jsonArray);
                     }
-                    if (Utils.isBlank(number)) {
+                    if (!Utils.isBlank(number)) {
                         jsonObject.put(K_NUMBER, number);
                     }
                     res = jsonObject.toString();
```

**Comment by renyuneyun** [comment]
Thanks for spotting that!
I believe you are right. Would you like to create a pull request, or shall I directly change it?

**Comment by shieldwed** [comment]
Thanks very much, I don't mind :wink:
