### ISSUE TITLE
Date condition doesn't take year into account?

### ISSUE THREAD

**Issue by perepujal** [renyuneyun/Easer#302]
Date conditions that should happen past next year but before current month/day count as satisfied and triggers the associated action.

**To Reproduce**
Set a condition -> date -> 03/01/2021
03/01 < curremt 06/01   2021>2020 so it should not trigger until next year
Associate an action to the recently created and see how the action is triggered.

LineageOS 14.1 custom build
easer beta 0.8.pre3 from f-droid

**Comment by renyuneyun** [comment]
Thanks for reporting.
Indeed, there is a problem in the initial check. I'll fix it soon.
