### ISSUE TITLE
Crash pivot-menu

### ISSUE THREAD

**Issue by PsyEng** [renyuneyun/Easer#310]
**Describe the bug**
Open the Povit-Menu will end in a crash, it doesn't matter if I clear cache or something else. Errorlog is always 100% the same. 

**To Reproduce**
1. Go to main screen
2. Click on bacon icon
3. Click on Povit-Menu
4. See errorlog

**Expected behavior**
Open the Povit-Menu^^

**Error log:**
[2020_01_17_16_40_35.log](https://github.com/renyuneyun/Easer/files/4078400/2020_01_17_16_40_35.log)

**Extra phone information:**
 - ROM: DerpFest 10-Beta-Official-raphael-20191218
 - Build-Number: QQ1B.191205.011
 - Kernel: 4.14.159-iMMENSITY+ #5 Wed Dec 18 23:15:49 IST 2019

**Comment by PsyEng** [comment]
Sry, I didn't expect, there's an stable version of the app, but found it, after reinstalling. The stable version also has the same bug. 

[2020_01_17_20_12_30.log](https://github.com/renyuneyun/Easer/files/4078554/2020_01_17_20_12_30.log)

**Comment by renyuneyun** [comment]
Hi there,
I think they are two different bugs (as you may already be aware in #309).
The bug you reported is really strange... Can you confirm is there any Scripts (see the Data section) already? Or, does this happen on a new / empty installation?

**Comment by PsyEng** [comment]
Hi,
I used the app, made some scripts and then added a script to autostart Spotify and resume play. After this, the povit menu was completely broken. It doesn´t matter, if I reinstall the app or use my old data. Clear cache or anything else, doesn´t do anything. 

The first logfile is from the beta and the second one is from the stable version. Both have the same behavior, but I´m not sure, if I can open the povit menu, if I add a script in the stable version.

Sry, if something is unclear. Let me know what exactly you need and I will provide you as much information, as possible.

Thanks for your work and support :)

**Comment by renyuneyun** [comment]
Thanks for confirming. So I would say that's two different crashes, though both happening on the Pivot page.

I just published a new beta release which (hopefully) fixed the crash of an empty Pivot (but not the other = the bug you initially reported in this issue). Please could you post another log file if Easer still crashes? This release should have a better log file, with method names not being obfuscated.

**Comment by idealist1508** [comment]
I think i know what it is.
Here are the steps to reproduce:
* Create some bondition for example Battery Level
* Create Script with this Condition but without any Profile
* Change to Pivot View => App Crash

**Comment by PsyEng** [comment]
> I think i know what it is.
> Here are the steps to reproduce:
> 
>     * Create some bondition for example Battery Level
> 
>     * Create Script with this Condition but without any Profile
> 
>     * Change to Pivot View => App Crash

Absolutely genius. I didn't get it, that I removed the profile from one of my scripts, because I didn't see, there's an option to deactivate the script. I assigned the profile to the script in my beta version and now it works fine. Many thanks to you. 😊

I would close the issue, but I think it's better to repair this little bug, if it is little.

**Comment by renyuneyun** [comment]
That's strange. I accidentally reproduced it on my side, but after deleting some Scripts, I can no longer reproduce it...?
Even after I removed all Scripts and followed @idealist1508 's example, the problem does not appear.

**Comment by idealist1508** [comment]
You right. One script is not enough. I made a second one as above but with a connected profile.
Here is a exported data: [Easer.2020-01-29.07_11_34.zip](https://github.com/renyuneyun/Easer/files/4129851/Easer.2020-01-29.07_11_34.zip)

**Comment by PsyEng** [comment]
One script is enough, at my side. If I remove the profile from only one script, the app crashes at the time I open the povit menu. I recreated the crash with different profiles. Both are after removing the profile and trying to open the povit menu. After relaunching the app and add the profile back to the script, all works fine.
Here are both files. If you need more, let it know me. 
[2020_01_29_20_20_08.log](https://github.com/renyuneyun/Easer/files/4130322/2020_01_29_20_20_08.log)
[2020_01_29_20_22_26.log](https://github.com/renyuneyun/Easer/files/4130328/2020_01_29_20_22_26.log)

**Comment by PsyEng** [comment]
Okay, I've an update for you.
I've updated my system:

ROM: Evolution X 4.0 | Official 
Build: QQ1B.200105.004
Kernel: 4.14.168-iMMENSITY #1 Tue Jan 28 10:38:29 UTC 2020

Raser version: 0.8-pre3-beta5

Now, I can open the povit menu without any problems. It doesn't if I've a profile assigned to the script or not. I will test later, if the problem behaves on the stable version and maybe on other older beta versions, which u should do, to sort out the problem. Maybe it was a huge bug on my end, I don't know. If you need any further informations, let me know it and I will help you 😊

**Comment by renyuneyun** [comment]
Thanks @idealist1508 and @PsyEng. I did some tests and believe this is indeed a problem of the GraphView library, as you can see in the (back-)referenced issue (from GitHub).
Let's see how that goes and hope it will be solved soon.

**Comment by PsyEng** [comment]
You're welcome, I hope the bug will get fixed fast, but, like I said, at my end, it's fixed now, but I believe, you only got a workaround, which don't solve the problem by itself.
Nice to see activity.

**Comment by PsyEng** [comment]
I've found the next bug -.-

Same behavior like the last time, but different way. This time, it was an accident.
I created a script, which has two child scripts with a profile. Then I unlinked the main script, from the child scripts and the app crashed.
Log will be append, questions are welcome.

**Comment by PsyEng** [comment]
I closed the issue, it's not updated since over a year and I don't use Easter anymore. If someone whish to re-open it, you're welcome.
