### ISSUE TITLE
version of the app in the app

### ISSUE THREAD

**Issue by jpggithub** [renyuneyun/Easer#33]
Please add the version of the app somewhere (in the About menu for example)

You could also give the website addtess of the code.

**Comment by renyuneyun** [comment]
Whoops, I forgot that :P I'll add it.

In case needed: we can also see the version in the system app setting page.

**Comment by renyuneyun** [comment]
Added in 334102f :)

Version is now shown in the Settings page (the last item) :)

I forgot to mention: the *About* page already has the repo address (from the first FAB).
