### ISSUE TITLE
last version not in the f-droid repos

### ISSUE THREAD

**Issue by jpggithub** [renyuneyun/Easer#35]
In https://github.com/renyuneyun/Easer/issues/32, it seems that the last version of Easer is v0.3.7.
The version on f-droid is 0.3.6.1.
There is a problem in the automatic process or it is not an automatic process ;-)

By the way, is there a "release notes" place for Easer? Very useful to see the evolution of this app.

**Comment by renyuneyun** [comment]
Indeed it's an automatic process, but the process could take some time (days). Hope F-Droid guys won't break it again :P

I made a check just now, and saw the build information is there although the app information has not yet been updated. Let's wait for a few more days (I guess one or two days would be sufficient) to make it synchronized.

This could be observed in the history of f-droid wiki.
For example, [history including bots](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&hidebots=0) or [easer lastbuild](https://f-droid.org/wiki/index.php?title=ryey.easer/lastbuild&redirect=no).

**Comment by jpggithub** [comment]
Ok, thank you for the link of the changelog. I have searched a Release notes file... Ouch! :-/ I asked fdroid guys to add it in the links .
Last version is now in the fdroid repos so everything is fine now ;-)
