### ISSUE TITLE
Crash when creating cell event

### ISSUE THREAD

**Issue by johnnydvc** [renyuneyun/Easer#37]

**Comment by johnnydvc** [comment]
The app just crashes when I try to create a new event for a cell area.

**Comment by renyuneyun** [comment]
Hi, did you grant Easer the permission "access coarse location" (assuming you are using android 6+)?

**Comment by johnnydvc** [comment]
That was the issue, thank you. Do you plan to implement a location learning mode like in the apps Llama or Automate? Because when I'm at home I have several cells.


Am 10. Oktober 2017 23:12:26 MESZ schrieb renyuneyun <notifications@github.com>:

**Comment by renyuneyun** [comment]
@johnnydvc 
I'm not sure if I understand correctly, but you can add several base stations in Easer. You just need to click the button and it would "add" one more base station (if it's not already in the list) -- the only issue is you need to know you (your phone) are under a different base station.  
By the way, there is a data format change (especially for cell location) in v0.3.9 (which will appear in the f-droid repo a few days later), but backward compatibility is maintained (by changing the old format to the new format).

Good to know these apps. I'll have a try on them to see what Easer could learn from them. A quick glance of them tells me they are very similar to the current Easer functions (or, should I say Easer is similar to them XD?), but anyway the final goal of Easer is not the same.
