### ISSUE TITLE
profile for airplane mode 

### ISSUE THREAD

**Issue by kilroythe5th** [renyuneyun/Easer#38]
it would be useful to have a profile for airplane mode for battery saving

**Comment by duttyend** [comment]
I second this, it would be awesome !

**Comment by renyuneyun** [comment]
I also like it, but unfortunately this function won't work when Easer run as a **normal** app. The rooted features will be added (the settings section) a bit later (currently I plan to add it after dynamically controling the enabled plugins).

If Easer could get **root permission**, then there is way out. But I'm not sure how likely people would actually like to run Easer on a rooted device (I am one).

(Perhaps switching airplane mode will also work if Easer is installed as a system app. But I am not sure whether this is generally true or not...)

**Comment by duttyend** [comment]
Thank you so much for your detailed answer!
Either way (by root or as a system app) would be fine.
Let me know if you need any testing.
Have a great day!

**Comment by kilroythe5th** [comment]
some other apps, like file managers, have an option in the settings to enable "root operations". Such an option wouldn't have to be enabled by default, but could be enabled by the user in the settings, if desired.

**Comment by renyuneyun** [comment]
v0.4.4 now has the option to enable "root features".
In v0.4.4, only "mobile data" (cellular) changes it behaviour under root.
Airplane mode will be added later.

**Comment by duttyend** [comment]
Awesome, thank you so much !
