### ISSUE TITLE
reply Text/sms placeholders

### ISSUE THREAD

**Issue by gar-onn** [renyuneyun/Easer#382]
I can't get placeholders to work for SMS destination.
Would there be an option to create an option to reply to a sender.
An alternative would be for the value "000" (or other) to be automatically set to the placeholder `<<sender>>`.

**Comment by beardhatcode** [comment]
It likely will suffice to adjust this file such that `placholders` also looks for placeholders in the destination part and that applyDynamics also affects the destination.

https://github.com/renyuneyun/Easer/blob/c319ee4cc2e5ae216cac2681c3024ba97a261752/app/src/main/java/ryey/easer/skills/operation/send_sms/SmsOperationData.java#L141-L152

**Comment by renyuneyun** [comment]
Thanks for spotting that. Indeed that should be possible.
I'll work on that when I have time (sorry, time is really a constraint for me recently...). But it should be simple.

**Comment by renyuneyun** [comment]
Hi, v0.8.2.1-beta (published just now) would probably solved this. (There would be a delay for it to appear on f-droid.)
Please have a test and report back if you are interested :)

Otherwise, I'll close this issue in a few weeks.

**Comment by gar-onn** [comment]
Hi,

This still doesn't seem to work, since placeholders can't be inputted in the sms field. See image.

I would suggest trying the following script since "N" can be inputted. 

```bash
sed -i 's/destination\.raw/\0.repalce(".*NNN.*","<<sender>>")' app/src/main/java/ryey/easer/skills/operation/send_sms/*.java
```

![Screenshot_20210919-142936](https://user-images.githubusercontent.com/32686991/133927527-47038ed9-579d-4b40-8099-61e2f90fa1a3.png)

**Comment by beardhatcode** [comment]
@gar-onn , The solution you propose is likely device specific.

- Have you tried pasting the text "`<<sender>>`" in the field. 
- Have you tried switching keyboards to insert the text?

**Comment by gar-onn** [comment]
I have tried these things, even pasting text in the field, which doesn't work. But I wouldn't suggest allowing text in the number input field, since these might cause other issues.

Another option would be a checkbox in the profile, or an `return sms` option in the list.

**Comment by renyuneyun** [comment]
@gar-onn Thanks for the information.
That is probably because of the format specification/check for the receiver field to be numbers only.
I'll try to see if that is the case, and change it accordingly.
