### ISSUE TITLE
App should refresh itself every few seconds to update itself

### ISSUE THREAD

**Issue by DUOLabs333** [renyuneyun/Easer#384]
I have a script that checks to see if a widget has been pressed; if so, it executes a profile. The problem is, I can't execute it again by pressing the button, because the app hasn't updated itself yet. So, to the app, the event is still being satisfied. I can fix this by pressing the refresh button on the Outline page. So, a simple way to fix this is to set up a loop where every so seconds, you execute the same action as the refresh button.

**Comment by renyuneyun** [comment]
Hi, have you checked [Advanced Event Control](https://github.com/renyuneyun/Easer/wiki/Advanced-Event-control)?
Chances are that you accidentally set "persistent" when editing your script.
