### ISSUE TITLE
Two buttons block the texts behind

### ISSUE THREAD

**Issue by yuhuitech** [renyuneyun/Easer#386]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on those welcome pages, **there are two buttons blocking the texts behind, which might not be apt**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 0.8.2-beta2, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that those two buttons are separated from the texts behind completely.

**Steps to reproduce the behavior:**

1. use the largest font and display in the display setting
2. open this app for the first time, and scroll between those welcome pages
3. this error could be seen

**Screenshot**

(The overlap is marked in red)

<img src="https://user-images.githubusercontent.com/25502419/129825461-576edebc-72fe-49b5-899c-cb19fda45450.png" alt="copy" width="250"/>  <img src="https://user-images.githubusercontent.com/25502419/129825464-bf780bab-8def-45cb-81e5-ba0c280114f3.png" alt="copy" width="250"/>

**Environment**

1. Version of Easer (beta): 0.8.2-beta2
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by renyuneyun** [comment]
Glad you provided a PR. Thanks! I'll close this issue as the PR is merged.
