### ISSUE TITLE
FloatingActionButton to add events and profiles

### ISSUE THREAD

**Issue by Jiikuy** [renyuneyun/Easer#39]
It would be nice to have a FloatingActionButton in the events and in the profiles menu to add events and profiles. This would be much more convenient than having to click on the three dots and choosing "Add".

**Comment by renyuneyun** [comment]
Fixed in 11734ba6cff2ce1002796108951e0f97b23a5f88

(I was planning to add it after the re-design of the page to list events, but many people are calling for such a FAB... LOL)
