### ISSUE TITLE
findSkill by data class is not compatible with intent skills

### ISSUE THREAD

**Issue by mvn23** [renyuneyun/Easer#401]
When creating a new profile with any `intent`-type skill (`activity`, `broadcast`, `service`), that skill always gets saved as an `activity`.
I tracked it down to be caused by the fact that the plugin is looked up by comparing the data storage class to that of all plugins, but all `intent`-type skills use the same data storage class (`IntentOperationData`).
Unfortunately I lack the skills to prepare a fix for this issue.

To reproduce, create a new profile with either a `broadcast` or `service` skill attached to it. Save it, then edit it. It is now loaded as an `activity` instead.

**Comment by renyuneyun** [comment]
Thanks for spotting this! That's very clear explanation.

That mechanism is indeed problematic. I'll improve it soon.

In the meantime, bear in mind that there are also some issues with the *service* operation -- not in the way they work, but in the way they receive specifications. I was trying to provide a better unified operation for them, but did not progress far enough.

**Comment by renyuneyun** [comment]
Hi. Does this issue still exist on v0.8.2.3-beta2?
I hope this is fixed by [17556ca](https://github.com/renyuneyun/Easer/commit/17556cab083234050767efc48b6b7510fe056224).

**Comment by mvn23** [comment]
A quick test indeed confirms the fix! Awesome!
