### ISSUE TITLE
Add support for NFC tag events

### ISSUE THREAD

**Issue by lekv** [renyuneyun/Easer#42]
It would be great to have an event that triggers when NFC tags are scanned, for example to activate car mode when entering the car.

**Comment by renyuneyun** [comment]
Hmm, sounds great.

I'm not familar with dealing with NFC now, so implementing this may take a while (plus I also don't have NFC tags on hand so I can't test it...). Hope good news will come ;P

**Comment by sabi0** [comment]
You don't need a dedicated NFC tag, as far as I understand. Anything "contactless" uses NFC.
Bank cards, public transport tickets - if you can "tap to pay" it has NFC.
These are not writable, of course. But I guess you don't need to write anything specific as long as each "tag" has a unique ID which you could save in an event.

**Comment by renyuneyun** [comment]
Thanks @sabi0 :>

The NFC Tag event is added in v0.5. (Thought due to a strange f-droid bug, the date when v0.5 enter the repo is unpredictable... Maybe a few days later, maybe weeks...)

I'm closing this issue. Feel free to open new issues is the function doesn't work weel.

**Comment by natrius** [comment]
@lekv @sabi0 
Have you tried it and can you give me an example? How to set one specific usecase with NFC? When i scan an NFC-Tag it opens the android-own nfc-reader but it does not seem to trigger Easer.

**Comment by renyuneyun** [comment]
@natrius 
Hi,
First, did you grant Easer the permission to access NFC?
Second, when using this Event, you should put the device's ID to the text field (this process can be done automatically if you press the button next to the text field, and scan your NFC tag while you are in the new (almost blank) activity).
