### ISSUE TITLE
Easer is not fullscreen by default

### ISSUE THREAD

**Issue by flexagoon** [renyuneyun/Easer#424]
**Describe the bug**
![Screenshot_20220227-183201_Easer](https://user-images.githubusercontent.com/66178592/155888874-7ccb9e3b-042c-4e07-84d9-1926f3b3b8ef.png)

**To Reproduce**
1. Use a phone with a long screen (OnePlus 7T Pro in my case)
2. Launch Easer

**Expected behavior**
Easer takes up the full screen height

**Extra phone info (please complete the following information):**
 - ROM: LineageOS 18.1

**Additional context**
This can be fixed by manually setting Easer as a full screen apo in the phone settings. However I'd like this to be the default

**Comment by flexagoon** [comment]
Perhaps this is related to Easer targeting outdated Android versions.

**Comment by renyuneyun** [comment]
Thanks @flexagoon for the hints on the potential cause!
Do you have some pointers (URLs) to where this is discussed?

I noticed this issue previously, but it disappeared later (after switching ROM), so I thought it was a problem with my ROM.

**Comment by flexagoon** [comment]
This seems to be fixed in 0.8.3
