### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [renyuneyun/Easer#429]
**Describe the bug**
```
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalStableRelease'.
> Could not resolve all artifacts for configuration ':app:stableDebugCompileClasspath'.
   > Could not find com.github.AppIntro:AppIntro:4.2.3.
     Required by:
         project :app
```

Could you please take a look? Thanks!

**Comment by renyuneyun** [comment]
Thanks for reporting. This is a known issue, and I have reported it earlier: https://github.com/renyuneyun/Easer/issues/414#issuecomment-1086381634 and  https://github.com/AppIntro/AppIntro/issues/1008

But it doesn't seem like to be fixed recently (if at all). I'm publishing new beta versions with the dependency updated.

**Comment by linsui** [comment]
Thanks! Then the new version should be picked up automatically.
