### ISSUE TITLE
[Bug:] Notifications not shown anymore in 0.8.3-beta

### ISSUE THREAD

**Issue by just-Nob** [renyuneyun/Easer#437]
**Bug Description**
After updating to the latest version 0.8.3-beta, no script notifications are displayed in the status bar area anymore (but Easer's "main app notification is still there!), neither if triggered by a script automatically, not of triggered manually.
I checked the system's notification settings for Easer to ensure that they weren't disabled by accident, but everything's fine here.
When going back to v. 0.8.2.3-beta2, notifications are shown again, upgrading to 0.8.3-beta one more time disables notification output again.

**To Reproduce**
1. Update to 0.8.3-beta
2. Trigger any profile including a "notification" operation.
3. Pull down the device's status bar to check if the notification has been displayed.

**Expected behavior**
The notification is displayed in the status bar.

**Error log:**
Will be made up if needed.

**Extra phone info (please complete the following information):**
 - ROM: ArroOS 11
 - Device: Poco X3 NFC
 - Root: yes

**Comment by renyuneyun** [comment]
Thanks for reporting. I can confirm this. Probably I'll need to figure out what changes in Android/SDK/AndroidX version made this happen.

**Comment by just-Nob** [comment]
Seems to be fixed in 0.8.3-beta3.
