### ISSUE TITLE
More fine-grained event conditions

### ISSUE THREAD

**Issue by jdoe0** [renyuneyun/Easer#5]
Currently, the attributes in each event are activated when the specified condition becomes true. For example, if `Cell Location` is selected, the chosen profile will be activated when the user enters the specified location. It would be nice to be able to activate a profile when the condition becomes false as well. For cell location, this would correspond to the user leaving the chosen location. This would allow the user to, for example, have the phone automatically enter silent mode at the office and turn ringtone back on upon leaving.

**Comment by renyuneyun** [comment]
Yes, that's on the agenda (or say, the [TODO](https://github.com/renyuneyun/Easer/blob/master/TODO.en.md) list).

What I want to achieve is more than `true` and `false`. I want to explicitly split the `true` condition to more accurate ones (e.g. currently they are all `after`, but there obviously exists one more as `on`).

That requires the change to at least the events part, data storage part (though few) and the UI part. However, I'm currently busy revising for my exams, so I will only have time to do such a big change after the exams (which is about a month later).

**Comment by renyuneyun** [comment]
You may have a try on v0.3.1 (actually starting from v0.3.0), which supports more event types. (Please close the issue if you had a try and felt it good enough.)

Feel free to ask for more types if you need them.

**Comment by jdoe0** [comment]
Thanks! Seems to work fine for me.
