### ISSUE TITLE
Latest updates to Easer are not posted on F-Droid

### ISSUE THREAD

**Issue by craftyguy** [renyuneyun/Easer#53]
@renyuneyun I'm assuming you are the one responsible for 'maintaining' Easer on F-droid, do you know what's up? I know the F-droid system was having issues with building apps, which led to several days of no updates for any apps being posted, but that seems to be resolved now as other apps I have installed through F-droid are now receiving updates.

**Comment by ildar** [comment]
No. 3 apps per day is the same as nothing. I guess that the day it's fixed
we'll see a few tens of apps, maybe 50.

**Comment by renyuneyun** [comment]
Good guess :) Indeed I am.

I'm not sure whether that's solved or not, but Easer hasn't been rebuilt as for now. The last attempt for a build was on [30 December](https://f-droid.org/wiki/page/ryey.easer/lastbuild_50). In theory, any failed builds will be retried (until success?).

I have also posted the question on f-droid forum, but no one really knows why. One guess is the f-droid build server lacks (a correctly-configured) Android SDK 27.

Currently, it seems the only way to get update is not through f-droid. I'm aware that requires uninstallation, but luckily we have "export" and "import" in Easer.

**Comment by craftyguy** [comment]
I'll close this issue since you are aware of the problem and we're just waiting for the f-droid folks to figure out how to be a reliable app distributor.
