### ISSUE TITLE
App controls unresponsive for 'event' and 'scenario'

### ISSUE THREAD

**Issue by craftyguy** [renyuneyun/Easer#58]
To reproduce this:

1) tap the + to add a new event or scenario (does not matter which) under the appropriate section in the app

2) swipe the swipe view control thing at the bottom left or right

After doing the above steps, the radio buttons and text fields presented when editing a new or existing event or scenario do not always react to finger taps. The buttons at the top (the 'X', 'save' and 'menu') do not work at all.

Strangely enough, I can still swipe the swipe view thing.

When this occurs, the phone's back button also does not function.

There was nothing interesting in the easer log, but here are the contents just in case (after I tapped around a bit in a new event)

```
1516846746524,2018.01.24 18:19:06.524,ASSERT,PRETTY_LOGGER,======Easer started======
1516846746856,2018.01.24 18:19:06.856,DEBUG,PRETTY_LOGGER,Permission for plugin <cell location> not satisfied
1516846749524,2018.01.24 18:19:09.524,VERBOSE,PRETTY_LOGGER,item: Scenario
1516846749539,2018.01.24 18:19:09.539,VERBOSE,PRETTY_LOGGER,All profiles: []
1516846749541,2018.01.24 18:19:09.541,DEBUG,PRETTY_LOGGER,reloadList()
1516846749542,2018.01.24 18:19:09.542,VERBOSE,PRETTY_LOGGER,All profiles: []
1516846750396,2018.01.24 18:19:10.396,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846750445,2018.01.24 18:19:10.445,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 0
1516846750446,2018.01.24 18:19:10.446,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 0
1516846750448,2018.01.24 18:19:10.448,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846750505,2018.01.24 18:19:10.505,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 0
1516846750506,2018.01.24 18:19:10.506,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 0
1516846750511,2018.01.24 18:19:10.511,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846750527,2018.01.24 18:19:10.527,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 0
1516846750528,2018.01.24 18:19:10.528,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 0
1516846754487,2018.01.24 18:19:14.487,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846754499,2018.01.24 18:19:14.499,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 0
1516846754499,2018.01.24 18:19:14.499,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 0
1516846754501,2018.01.24 18:19:14.501,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846755561,2018.01.24 18:19:15.561,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846755682,2018.01.24 18:19:15.682,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846755802,2018.01.24 18:19:15.802,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846755919,2018.01.24 18:19:15.919,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846755964,2018.01.24 18:19:15.964,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846755975,2018.01.24 18:19:15.975,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 0
1516846755978,2018.01.24 18:19:15.978,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 0
1516846756045,2018.01.24 18:19:16.045,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846756163,2018.01.24 18:19:16.163,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846756273,2018.01.24 18:19:16.273,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846756392,2018.01.24 18:19:16.392,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
1516846756506,2018.01.24 18:19:16.506,DEBUG,PRETTY_LOGGER,[FillDataJob] tick on 1
```

**Comment by renyuneyun** [comment]
Strange, I can't reproduce this problem...
I tried
1. create a new Scenario
2. create a new Event
3. edit a Scenario
4. edit an Event
They all work without problem...

**Comment by craftyguy** [comment]
Hmm. I'm on Android 8.1.. do you have an 8.1 device to try this on, or perhaps the emulator?

Later on when I have more time I can reproduce this on my device with logcat going to see if there is anything interesting printed there.

**Comment by renyuneyun** [comment]
Hmm, do you know any 8.1 emulators? I can only find ~8.0.

**Comment by craftyguy** [comment]
I don't know of any, if the official android emulator thing from google doesn't support 8.1..

I recorded my screen showing this issue. Unfortunately the app I used to record the screen does not show screen taps, but the sections of the video towards the end when nothing is happening on the screen are me actually tapping the controls at the top of the app (back, menu, save).

https://craftyguy.net/pub/recording_20180127_113905.mp4

**Comment by craftyguy** [comment]
I have figured out how to easily reproduce this: when prompted to allow calendar access to Easer, deny it. Then when you swipe past the calendar widget in a new event, the interface becomes unresponsive.

IMHO, users should be able to deny permissions to Easer for certain things without it breaking. For instance, I will never use the calendar feature and so I want to disable the permission for it to minimize any potential data leaks if easer were ever to be compromised.

**Comment by craftyguy** [comment]
I have figured out how to easily reproduce this: when prompted to allow calendar access to Easer, deny it. Then when you swipe past the calendar widget in a new event, the interface becomes unresponsive.

IMHO, users should be able to deny permissions to Easer for certain things without it breaking. For instance, I will never use the calendar feature and so I want to disable the permission for it to minimize any potential data leaks if easer were ever to be compromised.

**Comment by craftyguy** [comment]
@renyuneyun
A potential fix for this is to disable plugins for which Easer does not have permission to access data for.

For example, if I deny calendar access to Easer, and uncheck the calendar plugin in Easer, I do not hit this issue. Is it possible to have Easer automatically disable plugins when it is denied access to the data that the plugin needs?

**Comment by renyuneyun** [comment]
Thanks for the info. Now I have a guess of the potential cause.

Actually there is some problem in the handling of the post-request signal. I had a plan to revise that part later, but now it may be the time to check it.

**Comment by renyuneyun** [comment]
I suppose v0.5.5 would alleviate this problem. Is that the case?

**Comment by craftyguy** [comment]
It seems like it does! Thanks for the quick fix!


One small suggestion to make it more user friendly, instead of just graying out the option, it might be better to also display a message that this option isn't available because Easer was not granted the permission. This way the user can see the direct result of denying a permission, and they may have even forgotten they denied it in the past.
