### ISSUE TITLE
Crash on upon accessing location

### ISSUE THREAD

**Issue by jdoe0** [renyuneyun/Easer#6]
After clicking the button under `Cell Location` in the event creation dialog, the app crashes and the following error messages appear in the log.

````
E/AndroidRuntime( 4889): FATAL EXCEPTION: main
E/AndroidRuntime( 4889): Process: ryey.easer, PID: 4889
E/AndroidRuntime( 4889): java.lang.SecurityException: getCellLocation: Neither user 10089 nor current process has android.permission.ACCESS_COARSE_LOCATION.
E/AndroidRuntime( 4889): 	at android.os.Parcel.readException(Parcel.java:1684)
E/AndroidRuntime( 4889): 	at android.os.Parcel.readException(Parcel.java:1637)
E/AndroidRuntime( 4889): 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getCellLocation(ITelephony.java:2589)
E/AndroidRuntime( 4889): 	at android.telephony.TelephonyManager.getCellLocation(TelephonyManager.java:979)
E/AndroidRuntime( 4889): 	at ryey.easer.b.a.a.a$1.onClick(Unknown Source)
E/AndroidRuntime( 4889): 	at android.view.View.performClick(View.java:5637)
E/AndroidRuntime( 4889): 	at android.view.View$PerformClick.run(View.java:22433)
E/AndroidRuntime( 4889): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 4889): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4889): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 4889): 	at android.app.ActivityThread.main(ActivityThread.java:6126)
E/AndroidRuntime( 4889): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4889): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime( 4889): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
````
If the permission for location access is granted manually by the user through `App Info`, the app functions normally. Based on a quick search, this appears to be because Android 6.0 and later requires apps to use [Runtime Permissions](https://developer.android.com/training/permissions/requesting.html) to request some permissions considered dangerous in addition to listing them in the manifest file.

**Comment by renyuneyun** [comment]
Hmm, you are right. I didn't consider the permission issues.

I'll fix that when I have some free time (apart from revising for my exams).

**Comment by renyuneyun** [comment]
Finally, v0.4.7 now requires relevant permissions when you try to use a plugin (and also previously there was already a place promopting about possible un-granted permissions).

I'll close this issue. But please feel free to reopen it if that mechanism (i.e. not requiring the permission even on the first time) is not working. (However, for other permission problems, please open a separate issue.)
