### ISSUE TITLE
"Media control" operation doesn't work

### ISSUE THREAD

**Issue by matpower64** [renyuneyun/Easer#60]
#### Description:
I did a pretty simple setup where a profile (called "Music Skip") has the operation "Media Control" set to "Next" (I tried others too), which is then set inside an event (called "MiBand Button Press"), where it receives a broadcast from GadgetBridge.
#### Outcome:
The expected outcome would be a change in whatever the media player (Shuttle+ or YouTube) is playing. In reality it doesn't work at all.
### Additional info: 
Easer has root permission, it also complains about missing perms (apparently for notification) even though it has every permission asked allowed.
I tried doing the same using another operation for disabling WiFi and it works fine.
### System info:
**Device:** Redmi Note 3 Special Edition (kate)
**Android OS:** 8.1 (NitrogenOS 20180206)
**Easer version:** 0.5.3.2
[Logcat](https://github.com/renyuneyun/Easer/files/1717083/2018-02-12-14-41-01.txt)
[Easer log](https://www.dropbox.com/s/mgyg07zkx2q6os9/logs_0.csv?dl=0)

**Comment by renyuneyun** [comment]
Hi, Thanks for reporting.

For clearification: the "root permission" setting is quite experienmental, and it has nothing to do with permission checking yet. In the log, it seems you didn't grant Easer the permission to listen to notification (note there are two different components of Easer requiring notification permission; they can be enabled/disabled separately). That's why Easer says you don't have all permissions required.
Alternatively, you can "disable" certain functions of Easer (in Settings) and the permission check won't complain about them if they are disabled.

For media control, the log doesn't seem to contain any useful information. I suppose there is something related to `KeyEvent` (which is used inside the media control function) and am guessing it's (actually) related to the media player you use. Have you tried other media players (e.g. Vanilla Music)? Does media control work for it?

**Comment by matpower64** [comment]
Easer finally updated to 0.5.4, so I can confirm it indeed happens on the latest version too.

For the notification permission, yeah, I am pretty sure I gave it permission to listen to notifications. [Here's a screenshot of it.](https://user-images.githubusercontent.com/4731163/36385770-4bd17d9e-1572-11e8-87d3-0d890bd10dc6.png)

For the media control, yeah, I tried about 5 different players (Shuttle+, YouTube through YouTube Red, Phonograph and its fork, Vinyl and Vanilla Music) and they gave me the same result. [Here's a newer log.](https://www.dropbox.com/s/3ws7ldntyritokk/logs_0.csv?dl=0) I'll test it in another Oreo device later and try to test it in a Nougat or older too so we can check if it is a device/OS specific thing, as it seems to be receiving the input and it does work when I use another action such as turning wifi off.

**Comment by renyuneyun** [comment]
Hmm, the permission thing seems quite interesting (strange).
Those two components have almost the same code for permission check (and relevant stuff), so they shouldn't have any difference. Even there is a difference, it should be the `ringer_mode` one not acting correctly. However, the log indicates that `notification` is the one which doesn't function well...

Thanks in advance for your willing to help debugging on other devices.
I borrowed an OnePlus 3 (with Android 8.0, OxygenOS `OP3_O2_Open_31`) to test, and there isn't this problem.

**Comment by matpower64** [comment]
Sorry for the long delay, I had a lot of IRL stuff (college, no internet, etc), but I managed to test it in two different devices.
First, yeah, it doesn't complain about permissions anymore (I am pretty sure my ROM was glitching in this case, I ended up doing a clean flash between the first test and the second one IIRC).
Second, I ended up testing in two different devices, a Moto G 2013 with AOSPEx 8.1 (with some low RAM flags turned on) and a Moto G 2014 with stock 6.0, due to certain limitations of the low RAM flag (like no access to notifications), I ended up not logging it, but the behaviour is the same. As for the Moto G 2014, I got the log [right here](https://www.dropbox.com/s/kujj81zs52vakn0/G2_logs_0.csv?dl=0).

I want to confirm that I am not doing anything wrong, that's my current setup and it seems to work at least for WiFi toggling.
![screenshot_20180227-232905](https://user-images.githubusercontent.com/4731163/36766912-bb742958-1c16-11e8-8b33-ed4e128faff0.png)
![screenshot_20180227-232917](https://user-images.githubusercontent.com/4731163/36766911-bb3d97ee-1c16-11e8-9425-786ffdcc8dd0.png)

**Comment by renyuneyun** [comment]
I think I got the answer:
I'm [using `KeyEvent`](https://stackoverflow.com/questions/6352136/android-using-intents-to-control-media-player) to simulate pressing a physical button, but [some](https://stackoverflow.com/a/28290172/2854555) said this is blocked on some Android versions (for security reasons?).

I'll try other methods, e.g. [1](https://stackoverflow.com/a/40493288/2854555), [2](https://stackoverflow.com/a/17286986/2854555), [3](https://www.reddit.com/r/androiddev/comments/2ul9tw/android_simulating_playpause_button/).
