### ISSUE TITLE
App is not exporting anything. 

### ISSUE THREAD

**Issue by syedubair** [renyuneyun/Easer#66]
#### Expected behavior
When we try to export a profile or an event ti SD card, it should export them. 

#### Actual behavior
As we press the export option, the app does not export and is functional less. It doesn't do anything. 

#### How to reproduce
Save a profile or an event. 
Now go to settings from menu. 
Now to export click on the export button. 
App will not export anything. 

* App: Easer v0.5.5
* Operating system: Android Nought 7 - Moto g5 plus 

#### Recording Of The Bug
https://youtu.be/2WVQeApwKHc
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedubair/app-is-not-exporting-anything">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by pikim** [comment]
Did you give the permission to access the memory?

**Comment by syedubair** [comment]
Yes sir I did

**Comment by renyuneyun** [comment]
Hmm... My best guess is also that you haven't grant Easer the permission to write to external storage. That permission may not be checked on the Outline page's "permission" section.

If you confirm you have enabled that, could you post a log to help identifying what might go wrong?
Either logcat or Easer's logging (located under `/sdcard/logger/` if you have enabled logging in Easer's setting) will be enough.

**Comment by syedubair** [comment]
Yes sir. It worked fine now :) Sorry for the inconvenience.
