### ISSUE TITLE
Add support for muting

### ISSUE THREAD

**Issue by jo-so** [renyuneyun/Easer#7]
I would like to make my mobile phone at 9pm quiet. Can you add such a setting for profiles?

**Comment by renyuneyun** [comment]
Definitely it will happen. I like that too. (See [TODO](https://github.com/renyuneyun/Easer/blob/master/TODO.en.md))

The only problem is that I don't have time recently... So you may need to wait a while :P

**Comment by renyuneyun** [comment]
Just pushed v0.2.6 - it adds the ability to change ringer mode (silent, vibrate, normal).

Hope that's enough for now :)

**Comment by jo-so** [comment]
Yes, that's fine. :+1
