### ISSUE TITLE
12 and 24 hour clock

### ISSUE THREAD

**Issue by twikedk** [renyuneyun/Easer#75]
Enhancement: The ability to switch between 12 and 24 hour clock would be great.

**Comment by nedredmond** [comment]
So, in 24-hour clock mode, I can only select from 1-12. I have no idea if this is AM or PM. I had to switch to 12-hour clock to switch between AM and PM.

**Comment by renyuneyun** [comment]
@nedredmond It seems strange, as I can select AM/PM when using 12-hour mode. Could you open another issue and provider some more information?

**Comment by batmanscode** [comment]
> So, in 24-hour clock mode, I can only select from 1-12. I have no idea if this is AM or PM. I had to switch to 12-hour clock to switch between AM and PM.

Same here, thanks for the workaround

@renyuneyun where is the AM/PM button supposed to be?
