### ISSUE TITLE
Please more documentation or at least a simple walk through / howto

### ISSUE THREAD

**Issue by mark-orion** [renyuneyun/Easer#77]
This app looks great, but I cannot use it because I do not know how. Please create some documentation (in English) or at least a walk through / how to for the given examples:
"Set your phone to silent mode at 2 a.m"
"Turn on WiFi when approaching your home; turn off WiFi when leaving your home"
- How do I do this in the app ?

**Comment by renyuneyun** [comment]
Hmm... My fault.
Yes I'd also like to present some examples, but I have no idea where to put it to. You see, there is a website (built on top of github pages), but I'm not familiar with that toolchain and don't know how to make it better to suit more general needs (e.g. provide a set of examples with good display structure).

At this point, you may have a look at #62 where there is an example.

**Comment by renyuneyun** [comment]
A simple illustration for your first example:

1. Create a *Profile* named anything (e.g. `P1`), and add one *Operation* (Ringer Mode, set it to silent)
2. Create an *Event* named anything (e.g. `E1`)
  * Choose `P1` in the *Profile* selection (drop-down list)
  * Swipe to "Time" and set it at 2 a.m

That's all. You don't *have to* use a Scenario.

**Comment by renyuneyun** [comment]
I have updated a link to #62 in the wiki. Hopefully some people will find it useful.

I also acknowledge that the naming of each thing (Event/Scenario/Operation/Profile) is not great. I'd like to replace them with better names, and suggestions are welcome.

**Comment by renyuneyun** [comment]
Maybe #88 is a better place to continue discussion. I'm closing this issue (hope you don't mind :P).

**Comment by ildar** [comment]
J IMHO: the classic place for such docs is wiki, that's right. The new
breed looks in YouTube for such things now so it's a good idea for someone
to film step-by-step there
