### ISSUE TITLE
Operation: set preferred network type

### ISSUE THREAD

**Issue by talion86** [renyuneyun/Easer#8]
I would like to automatically set the preferred network type to "gsm only" when I am in a specific Wifi in order to use battery drainage due to low network signal.
Moreover I would like to change the preferred network type back to "GSM/WCDMA" as soon as I am NOT in that Wifi anymore, but I guess this would be possible when #5 is done.

Thank you for your work!

**Comment by renyuneyun** [comment]
Hi there,
I just briefed searched the web (only read a few pages) but it seems not possible for a common/normal app to control that state - apps can only *get* the state but can't *set*.

Maybe that could be done by acquiring root permission, but it would need to be delayed for more time (at least after the Settings page)...

For the "leaving" action, yes it's on agenda. But as you may already know from that issue, I can only try to implement it after my exams :(

**Comment by talion86** [comment]
Hi,
bad news, but thank you for the research!

**Comment by devmsv** [comment]
Is this planned with root? Or is not going to be implemented?
