### ISSUE TITLE
Easer crashes on screen rotate

### ISSUE THREAD

**Issue by macspeaks** [renyuneyun/Easer#81]
#### Expected behavior
App is suppose to be responsive on every screen mode, to enable phones with small screen use the landscape mode.

#### Actual behavior
App crashes when you want to add event or scenario and you rotate your screen.

#### How to reproduce
* Download Easer from F-droid
* Open the app
* Click on menu icon and choose event or scenario
* Click the plus button
* Rotate your screen

#### Device detail
* Device: Lenovo a5000 
* OS: 5.0.2
* Software version: Easer 0.5.5.4

#### Recording Of The Bug
<iframe width="560" height="315" src="https://www.youtube.com/embed/3bQn6NhAU9o" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@macspeaks/easer-crashes-on-screen-rotate">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by natrius** [comment]
Same here. In addition: bevore clicking pressing the (+) for a new scenario - rotating the screen causes the infoscreen about the events to come it again and again...

**Device detail**

- Device: Oneplus 3
- OS: LineageOS 8.1
- Software version: F-Droid Easer 0.5.6.1

Besides: 
Is there sort of a documentation for 2 or 3 common things to get an example? For example plug-in headphones start music, or read nfc in car and start bluetooth, navigation, etc. etc.

Greets
