### ISSUE TITLE
Bluetooth volume not changing

### ISSUE THREAD

**Issue by mase76** [renyuneyun/Easer#83]
Hi!
The (bluetooth) media volume does not change. I have set up to change the media volume to full when connecting to my car stereo. However the profile is loaded. All permissions are set. My system is Omnirom 8.1.0.

**Comment by renyuneyun** [comment]
Thanks for reporting.
I'll fix this soon.

(Note to myself)
`STREAM_BLUETOOTH` is not documented, but Android is using `6` for it (see https://stackoverflow.com/questions/4472613/android-bluetooth-earpiece-volume ).

**Comment by renyuneyun** [comment]
This should have been solved in v0.5.7 (which should appear anytime on f-droid).

Feel free to reopen this issue if it's still there.

**Comment by mase76** [comment]
No, bt volume does not change with 0.5.7.

**Comment by renyuneyun** [comment]
Just to confirm: are you using (in the new version) the "bluetooth" volume meter?
It's a separate meter, added in v0.5.7

**Comment by mase76** [comment]
Yes, I noticed and use the bt volume meter.

**Comment by mase76** [comment]
I installed 0.5.7.1. The bt volume does not change.

**Comment by renyuneyun** [comment]
They seem to be using the same one (and there is nothing to do with the new "bluetooth volume" I added in v0.5.7.1)...
Just to confirm: have you tried to treat "music volume" as bluetooth volume (when connected to bluetooth)?

**Comment by mase76** [comment]
Yes, I used bt volume, not music volume.

**Comment by renyuneyun** [comment]
Errrr, I mean that music stream is seen as Bluetooth volume (by Android)
when Bluetooth device is connected.

mase76 <notifications@github.com> 于 2018年5月5日周六 01:06写道：

**Comment by mase76** [comment]
I tried both. After connecting I see a volume dialog coming from Android, which sets the bt volume to half. I found no way to disable this. A2DPVolume also had problems in the past. But in this app you can add a delay until adjustment. After setting it to 6 seconds, it worked.

**Comment by renyuneyun** [comment]
Hmm, thanks for the info!

So the solution is simple adding a delay. That's why I don't see that since in my test I use "charge" as the trigger and bluetooth headset is always connected.

There are two solutions, but I'm not sure which one you (and/or other people) would prefer:
1. Keep only the "music" field, and tell the user they'll need to add a delay (which is possible in Easer, through chained events) if want to set bluetooth volume, and let them do that manually. This gives user more control, and is visible in the future (when a graph is used to show the relationship of those triggers).
2. Add a "bluetooth music" field, and silently wait for a few seconds (maybe configurable) to adjust the volume, and user is responsible to choose the correct one ("bluetooth music" or "music" [or both, but doesn't make sense]).

By the way, let me check: is "music" the only volume setting which will vary/change between bluetooth and non-bluetooth?

**Comment by mase76** [comment]
I would prefer the second. A delay of 6 seconds is the default in A2DPVol and works fine. When I connect a bt headset, Android or my ROM (Omnirom) sets bt volume to half. I don't know how to disable this. But Easer could override this by setting the volume 6 seconds later. Or you could make the delay configurable, maybe for all volume adjustments, because I don't know the behaviour when connecting wired headsets. Doing this with an event chain wouldn't look very nice.

**Comment by mase76** [comment]
With the delay option it works fine now.

**Comment by renyuneyun** [comment]
That's great.
Maybe this issue can be closed?

**Comment by mase76** [comment]
Yes, I think, it can be closed.
But I would suggest to add the delay option generally to the volume change, independent
from bluetooth. When the delay is not needed, it can be set to 0.

**Comment by renyuneyun** [comment]
Not sure if I understand you correctly: do you suggest to "move" the delay to the whole "volume" setting (in one Profile)?

**Comment by mase76** [comment]
Yes, so the delay can be set when needed, independent from the volume channel.

**Comment by renyuneyun** [comment]
Then I think it's better to chain a "delay"/"timer" event and set the volume there.

The reason why I prefer this way is because I'm planning to add a "visual graph" for the scripts (yes, the previously UI element called "event" is renamed to "script"), and the delay can be easily seen there.

**Comment by mase76** [comment]
But therefor the order of the elements in the chain must be changable.

**Comment by mase76** [comment]
I don't know what happened. Since a few days, the bt volume changes not to the prefered value. When I configure full volume, I get only about 60%. When I set half, I get only about 30%. The action itself works, including the delay.

**Comment by renyuneyun** [comment]
The order of elements are changeable, at least from what I understand. Maybe you are experiencing some problem related to the old unclear semantics (of Event/Scenario), but this should be solved when all suitable Events have been transferred to Conditions (,which is not yet happened, but is happening).


For the volume, I think this may be a result of using different metrics, and BT has a different "highest" value than non-BT volume. I think the only solution is to use percentage...

**Comment by mase76** [comment]
I did a fresh install of my rom. Now volume change works again as it should. For now...

**Comment by renyuneyun** [comment]
I'm closing this as the issue seems to be fixed.

Feel free to reopen it :)
