### ISSUE TITLE
Easer crashes on pressing the start button

### ISSUE THREAD

**Issue by SkyWheel** [renyuneyun/Easer#84]
Hi,
I'm using Xiaomi Redmi Note 3 Pro with the latest LineageOS 14.1 Nightly.
Easer crashes on all attempts to start it. It simply doesn't work.

**Comment by ildar** [comment]
Please adb logcat.

**Comment by SkyWheel** [comment]
Huh! Decided to do clean installation: uninstalled app, removed all traces of it. Then downloaded apk from github (the previous installation was from fdroid) . Enabled all required permissions,  enabled root. Now it starts fine🙂
So, next check is to repeat all steps with the fdroid version. I will update the issue after the reinstallation.

**Comment by SkyWheel** [comment]
Awesome! So, the fdroid version works as well!🙂
Thanks for your quick response guys!

**Comment by renyuneyun** [comment]
@ildar <:)

> He can't turn it on, as

Just to test my understanding: The title says 

> Easer crashes on **pressing the start button**

So I think Easer starts, but only crashes when the "start" (start service) button is pressed. Therefore, there should be some logs (though I suspect nothing useful will be inside, because it doesn't log *every* exception).
