### ISSUE TITLE
multiple cell tower's

### ISSUE THREAD

**Issue by Offerel** [renyuneyun/Easer#87]
I have found your app in some website. Currently, im using Llama to change my sound profiles on my device. Since Llama Development is a thing of long past times, i was happy to find your app. Currently, im a little bit confused how the things should work. I can make profiles and events and scenarios, but i didn't have any idea how i can connect them, so that they can work. But that's a other story, maybe we can hope for a small tutorial in the wiki section or a similar thing.

For now, a bigger question are the cell towers. In Llama i trigger most of my profiles with the help of cell towers. That's why i love this app. But in Llama, i can have more than one cell tower to trigger one event/scenario. I can record over time (lets say i stay for the next 2 hours at this location) all the cell towers my phone can see/connect. And later when i reach this "Location" build upon a group of cell towers, my phone reacts with the scenario. Is there any way in your app, to record a group of cell towers? When i look under "Event" or "Scenario" i found only 1 cell tower or better, only 1 cell tower was added to the textbox. Do i have to add more cell towers by hand? If so, should i seperate them by space, or comma or what other sign?

**Comment by renyuneyun** [comment]
If I didn't make any mistakes in recent versions, the cell location thing supports multiple cell towers - just push that "add" / "fix" button, and more will be added (if you are currently on a different cell tower).

Yes, I agree the document is not so well. Though, the #62 pointed in the wiki page should be a good example of what Event/Scenario/Profile are and how they work :)

**Comment by renyuneyun** [comment]
Closed as of not a bug and inactive.
