### ISSUE TITLE
Better usage of the back-button, better "outline"

### ISSUE THREAD

**Issue by natrius** [renyuneyun/Easer#93]
On my big cellphone its empty - you could show the buttons for "Script, Profile, Scenario" too. On top still the big "Running", just the name "running" inside the button too.
The "Profile, From event, Loaded time" moving to below the button and below that the three buttons for script, event and scenario.

The back-button.
When in "Scenario" or "Scripts" and pressing back, easer closes. Change that going back to the Outline / Overview every time before closing. 
I'm pressing back somehow always expecting the overview and ending in opening easer again :D

**Comment by renyuneyun** [comment]
Good suggestion. I'm also changing the "back" behavior. It will be presented in v0.6.

But I don't quite understand your first and second paragraph LOL
Could you provide a sketch?

**Comment by renyuneyun** [comment]
Hmm, that's expected in the current logic.
Would you like to see (whenever) on "Outline" page, pressing "back" closes Easer?

**Comment by renyuneyun** [comment]
I'm not sure if I understand you correctly (about the picture):
1. Put "running" (or "not running") inside the (green, or red) banner
2. Put another menu inside the "outline" page, in order to go to "Script", "Profile", "Scenario"

Is that what you mean?

**Comment by natrius** [comment]
Outline: 
Basically, yes. I would even go further and show it somehow else, new shot provided (now in github :p )
![rft3jpn_2](https://user-images.githubusercontent.com/7243447/40359501-4ef0d95e-5dc3-11e8-90af-ecab8e147701.jpg)
But the other menu - it was just an idea to fill the empty space. (And the current version in the left bottom corner would be sometimes useful imo)

@Back Button
Well, i go in this way:
Overview --> script --> profile --> scenario --> add new scenario
Now, what i'm expecting, when pressing back:
add new scenario --> scenario --> Outline --> exit Easer
And not:
add new scenario --> scenario --> profile --> script --> Outline --> exit Easer
I like to mention it does not go back to outline after script or profile or scenario. I hope you get now what i mean. 

So, yes, when i'm on the outline and pressing back, it should close Easer. Maybe just pop up a 2 second bubble with "Press again to close Easer", similar to the amaze file-explorer and some other apps.

**Comment by natrius** [comment]
Looks good now. I will use the app itself and if i stumble across something again, i will open a new issue. Thank you!
