### ISSUE TITLE
New script - UI broken

### ISSUE THREAD

**Issue by natrius** [renyuneyun/Easer#95]
When creating a new script (Task?) below the title there is something to choose 
```
Parent
Profile:
```

There are 2 separate lines, first line is "Parent script", second line is "Profile"
As suggestion, 3 lines:
Parent script:  Dropdown [List of available scripts]
Profile:  Dropdown [List of available profiles]
Scenario:  Dropdown [New inline scenario] and below [List of available scenarios]

For the first line - when editing a script, exclude this script from the "parent" dropdown :)

EDIT: For some reason i cannot upload a screenshot *shrug*

**Comment by renyuneyun** [comment]
Well, yes, the drop-down list is there, but the indicator (arrow) is (mis-)placed outside... I have fixed it, and the fix will be presented in v0.6.

Yop, you are right, the current one should be excluded from the "parent" list. But it doesn't end here. I should also check for loops...

It's a bit trickey for the last item. Until v0.5.8, there is only "Event" (and "Scenario", as mentioned in #94) in Easer; but I'm adding "Condition" (as in #86).
I changed this to a group of radio buttons in v0.5.9 (which is published, but not yet known by f-droid). You may have a try of it (or v0.6), and then present your new feeling :P

**Comment by renyuneyun** [comment]
The broken UI should have been fixed in 05657b2ab5d232029164440a5b78fc7c67c4922d (which is part of v0.6).

I'm closing this issue. But feel free to open another issue for changing radio buttons to drop-down list.
