### ISSUE TITLE
App crashes while clicking on convert data. 

### ISSUE THREAD

**Issue by Xeeshuu** [renyuneyun/Easer#97]
App gets crashed while clicking on convert data. 
### How to reproduce 
Go to the settings of app. 
Scroll down the page. 
And click on convert data. 

* Browser:Easer event
* Version:0.5.9.1
* Operating system :5.1.1

**Comment by ildar** [comment]
ha! +1. Logcat:
'''
Tue, 15 May 2018 09:08:02 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime: FATAL EXCEPTION: main
Tue, 15 May 2018 09:08:02 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime: Process: ryey.easer, PID: 20445
Tue, 15 May 2018 09:08:02 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime: Theme: themes:{default=overlay:org.cyanogenmod.hexolibre,
iconPack:system, fontPkg:org.cyanogenmod.hexolibre,
com.android.systemui=overlay:org.cyanogenmod.hexolibre,
com.android.systemui.navbar=overlay:org.cyanogenmod.hexolibre}
Tue, 15 May 2018 09:08:02 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
Tue, 15 May 2018 09:08:02 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at ryey.easer.core.a.a.f.b(Unknown Source)
Tue, 15 May 2018 09:08:02 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at
ryey.easer.core.ui.setting.SettingsActivity$a$6.onPreferenceClick(Unknown
Source)
Tue, 15 May 2018 09:08:02 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at
android.preference.Preference.performClick(Preference.java:996)
Tue, 15 May 2018 09:08:02 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at
android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
Tue, 15 May 2018 09:08:02 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at
android.widget.AdapterView.performItemClick(AdapterView.java:310)
Tue, 15 May 2018 09:08:04 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at
android.widget.AbsListView.performItemClick(AbsListView.java:1169)
Tue, 15 May 2018 09:08:04 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at
android.widget.AbsListView$PerformClick.run(AbsListView.java:3217)
Tue, 15 May 2018 09:08:04 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at
android.widget.AbsListView$4.run(AbsListView.java:4062)
Tue, 15 May 2018 09:08:04 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
Tue, 15 May 2018 09:08:04 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
Tue, 15 May 2018 09:08:04 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
Tue, 15 May 2018 09:08:04 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at
android.app.ActivityThread.main(ActivityThread.java:5471)
Tue, 15 May 2018 09:08:04 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
Tue, 15 May 2018 09:08:04 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

Tue, 15 May 2018 09:08:04 +0600: 05-15 09:08:02.003 20445 20445 E
AndroidRuntime:     at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Tue, 15 May 2018 09:08:04 +0600: 05-15 09:08:02.006   606  1097 W
ActivityManager:   Force finishing activity
ryey.easer/.core.ui.setting.SettingsActivity
'''

**Comment by Xeeshuu** [comment]
What should i do with this?

**Comment by ildar** [comment]
Nothing. This is for @renyuneyun

**Comment by Xeeshuu** [comment]
Is this logcat for reproducing this bug

**Comment by ildar** [comment]
no. this is diagnostic when the bug occurs

**Comment by natrius** [comment]
Same here, i can provide logcat if needed.

**Comment by natrius** [comment]
Got 0.6 today, conversion was working. No crash.

**Comment by renyuneyun** [comment]
Should this issue be closed now? :P

**Comment by natrius** [comment]
@Xeeshuu ?

**Comment by Xeeshuu** [comment]
Yes,you can close it know

**Comment by natrius** [comment]
@Xeeshuu  
FYI: You can close an issue by yourself, if you are the creator and think everything is alright. Just next to the green "Comment" button. :)
Just a general information for the future.

**Comment by renyuneyun** [comment]
Anyway, I'll close this ;-)
